### ISSUE TITLE
Datasets with valid bbox do not open in viewer page

### ISSUE THREAD

**Issue by DavidQuartz** [GeoNode/geonode-mapstore-client#1011]
ref @allyoucanmap's comment on https://github.com/GeoNode/geonode-mapstore-client/pull/1000

@DavidQuartz I tested locally and the dataset pages does not work when the bbox is valid the problem is related to this statement

https://github.com/GeoNode/geonode-mapstore-client/blob/c3423503c6d95fa700870fb1008c9ee6253f40b7/geonode_mapstore_client/client/js/epics/gnresource.js#L166

This is returning an undefined when there is not bbox error so Observable.of(undefined) that is breaking the app
We should use this approach instead

```js
...(newLayer?.bboxError
    ? [warningNotification({ title: "gnviewer.invalidBbox", message: "gnviewer.invalidBboxMsg" })]
    : [])
```

_Originally posted by @allyoucanmap in https://github.com/GeoNode/geonode-mapstore-client/issues/1000#issuecomment-1147258437_

**Comment by allyoucanmap** [comment]
connected to #961
