### ISSUE TITLE
Network error on creating a new map

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1037]
### Expected Behavior 
Users should always successfully be able to create and save a new map.
### Actual Behavior
Sometimes a network error is raised on saving a new map.

**Hint**: This is because sometimes the client makes a request to copy a URL instead of a new map api.
**Note**: This does not happen all the time.

### Steps to reproduce
1. Login to as admin/ user with add_resource perm
2. Click on `Add Resource > Create map`
3. Save the map.
4. Notice the request made when Network error is returned.

**Comment by DavidQuartz** [comment]
@marthamareal I am unable to replicate this issue. I have tried on my local geoonode instance and geonode-mapstore-client proxy but not once encountered the error.
I also tried throttling my network speed to simulate a slow 3G connection and still to no avail.

Can you provide any information that could help to replicate the issue?

**Comment by knl88** [comment]
I am also seeing the Network error on saving maps, when geonode 3.3.x is setup to use an external postgresql database that creates additional latency. Looks like the ` POST /mapstore/rest/resources/?full=true` request does not return in time and the save operation reports a Network error in the UI, but the map looks to be created successfully when listing maps. 

I don't see the Network error message when running the database on the same instance as geonode, but then the Geonode api returns faster with the 201 code for the post request.
