### ISSUE TITLE
Audio/image/video customization on GetFeatureInfo

### ISSUE THREAD

**Issue by ElenaGallo** [GeoNode/geonode-mapstore-client#1059]
The Audio/image/video link in the attribute table is no longer customizable on GetFeatureInfo.

**How to Reproduce**

- Open [this dataset](https://development.demo.geonode.org/catalogue/#/dataset/388)
- Follow the steps in the gif below:

https://user-images.githubusercontent.com/56537133/176451506-ec5af4f7-26f8-4f7a-9147-2476f592acab.mov

**Comment by giohappy** [comment]
@ElenaGallo I think this has always worked like this. The custom template is an HTML page. The variables are only replaced with the values of the fields, i.e. the URLs. If a user wants to show the media he will have to use the tools from the WYSIWYG toolbar

![image](https://user-images.githubusercontent.com/571129/178007753-0c40cb4f-373c-4d30-b5a4-bf60480a2045.png)

**Comment by ElenaGallo** [comment]
@giohappy you are right, the issue can be closed.
