### ISSUE TITLE
Metadata download

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1132]
We want to restore the ability to download the resource metadata file, as we had in previous GeoNode versions.

The proposal is to change the current "Export" button, inside the resource viewer action bar, into a "Download" dropdown menu:

![image](https://user-images.githubusercontent.com/571129/182339585-d11b5310-03d8-4b06-89f6-ca02c9c809ae.png)

 - Download
   - ISO Metadata -> link to ISO metadata file
   - Dublin Core Metadata -> link to Dublin Core metadata file
   - Data -> Export window

The best would be to open a modal for the metadata download to let the user choose the download format, but as a first step it could just have two buttons for the most commonly used metadata formats, ISO and Dublin Core.

The two links can be obtained from the resource response `links` array and select the two with `link_type = "metadata"` and `name = <ISO | Dublin Core>`.
Dataset and document endpoints also return the links property.
 
![image](https://user-images.githubusercontent.com/571129/182339352-30993835-d74f-4eef-94ee-32684d38f439.png)

**Comment by giohappy** [comment]
@DavidQuartz I would change the menu items, since at the moment it's a bit confusing.

Instead of:

 - ISO Metadata
 - Dublin Core Metadata
 - Export

I would do:

 - Data
 - ISO Metadata
 - Dublin Core Metadata

**Comment by DavidQuartz** [comment]
@giohappy I have opened an Issue for this [here](https://github.com/GeoNode/geonode-mapstore-client/issues/1156#issue-1346377981)
