### ISSUE TITLE
Disable / hide the charts button if a user doesn't have enough perms on the dataset

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1144]
**Problem:**

add a widget - Couldn't add a chart/table/counter - got this error "Please try to select another layer or widget type. The server doesn't provide the needed services for the layer and the widget type selected. Possible causes are: The selected layer is a raster layer; WFS service is not available; The WPS process gs:aggregate is not available" 

**Cause:**
If a user doesn't have "Download" permissions on a layer WFS services are forbidden, and charts rely on WFS.

**Solution:**
Disable / hide the charts button in case the user doesn't have enough permissions on that layer.

**Comment by marthamareal** [comment]
This works as expected with map layers on master.

However, the same error is available on choosing layers to add on dashboards and geostories. should we open another issue to address this or the error message is enough in these scenarios?
![aa](https://user-images.githubusercontent.com/20810749/190353702-fbdfd00f-75f2-4538-8be0-610129cd57f4.png)

**Comment by giohappy** [comment]
@marthamareal @DavidQuartz does it mean this control is only implemented for maps?

**Comment by DavidQuartz** [comment]
@giohappy yes it's currently only implemented in maps

**Comment by giohappy** [comment]
@DavidQuartz how long would it take to implement this check for the other resources?
