### ISSUE TITLE
Map definition is saved as string from migration script

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-mapstore-client#1148]
Hi,

in my tests a migration from geonode 3.2 to geonode 4 ends in broken maps. the reason is that the migration is missing a json.loads and hence writting the blob string as string:

https://github.com/GeoNode/geonode-mapstore-client/blob/d54a9b9ba5d8ed274bb8180ffba92c0612c5d37f/geonode_mapstore_client/migrations/0002_migrate_map_blob.py#L38

<img width="352" alt="Bildschirmfoto 2022-08-17 um 07 52 41" src="https://user-images.githubusercontent.com/20478652/185044643-d7cc24d0-fc2f-463e-b602-160d2c17cc78.png">

@mattiagiupponi I think you've added the migration. Is a PR okay for you that adds the json.loads as in the inital version again?

https://github.com/Hydrata/geonode/blob/b1b275a9913bd046c0eb93406ebad06bc07a2400/geonode/maps/migrations/0043_auto_20220428_0732.py#L21

**Comment by mattiagiupponi** [comment]
Hi @t-book 
I prefer to take a deeper look because in this comment https://github.com/GeoNode/geonode/issues/9252#issuecomment-1144657569 the migration was tested, and it worked (I also tried it on local and It worked).
if we add the json.load directly there, it may break the migration for other use cases. An "IF" or a "TRY" would be a safer choice, maybe something like:
```python
try:
     to_update['blob'] = json.loads(result[0][0] )
except Exception as e:
    to_update['blob'] = result[0][0] 
```

**Comment by t-book** [comment]
Good suggestion @mattiagiupponi I agree and will test it.

**Comment by mattiagiupponi** [comment]
@t-book did you have the chance to try it or should I prepare a branch for you?

**Comment by t-book** [comment]
Hi @mattiagiupponi 

so I finally had the chance to further test the migration. Unfortunately it looks an added check and json.loads will not fix my problems. My guess is the added json.loads still fails because of masked quotes.

```
        "featureInfo": {
          "format": "TEMPLATE",
          "template": "<div><div class=\"row\"><div class=\"col-xs-4\" style=\"font-weight: bold; word-wrap: break-word;\">GRAY_INDEX</div>                                         <div class=\"col-xs-8\" style=\"word-wrap: break-word;\">${properties.GRAY_INDEX}</div></div></div>"
        },
```

For now I've just converted the strings with some sql. Which works quite well for me:

```
UPDATE base_resourcebase dst  
SET blob = (src.blob #>> '{}')::jsonb 
FROM base_resourcebase src    
WHERE dst.id = src.id 
AND dst.resource_type='map';
```

As it looks that nobody yet faces this issue I will close here. We can reopen in case others struggle. 

Thanks for your help again !

**Comment by mattiagiupponi** [comment]
Hey @t-book 
That's strange, just as info, does this map comes from an even earlier version of geonode 3.2?
After your update, were you able to upgrade geonode to 4.x?
