### ISSUE TITLE
Rename Export and Rearrang Download menu items

### ISSUE THREAD

**Issue by DavidQuartz** [GeoNode/geonode-mapstore-client#1156]
I would change the menu items, since at the moment it's a bit confusing.

Instead of:

 - ISO Metadata
 - Dublin Core Metadata
 - Export

I would do:

 - Data
 - ISO Metadata
 - Dublin Core Metadata

_Originally posted by @giohappy in https://github.com/GeoNode/geonode-mapstore-client/issues/1132#issuecomment-1222062809_

**Comment by giohappy** [comment]
tested on development server. All fine.

**Comment by giohappy** [comment]
@ElenaGallo please add a test on Cucumber for the two new download links:

![image](https://user-images.githubusercontent.com/571129/186174138-56076fba-aeca-4527-ba84-9612119abfe9.png)
