### ISSUE TITLE
Update total when resource is removed from favorite

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1169]
**Steps:**
- Favorite a resource
- Go to Favorites
- Preview resource
- remove the resource from favorite using the favorite icon in the preview
Notice that the results are updated but the total is not

![aa](https://user-images.githubusercontent.com/20810749/187938423-e0c38b66-8c13-4c25-a260-ba687e79708e.png)

**Comment by giohappy** [comment]
merged, waiting for the deployment on master demo @marthamareal then you can test it.

**Comment by giohappy** [comment]
@DavidQuartz there's still a problem as we saw together a few days ago. The count keeps increasing even if you umark the resource. Every time you click the favorite button the counter increases.
