### ISSUE TITLE
Geonode Download filtered dataset, where filter is based on another layer

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1192]
@nagyrobir commented on [Tue Aug 16 2022](https://github.com/GeoNode/geonode/issues/9856)

## Expected Behavior
I have a point layer uploaded in Geonode, via the QGIS geonode plugin. I can view the dataset, everything works as expected.
I have a polygon layer created through geonode with one polygon. Works as expected.
When i try to filter the point layer by the polygon layer, the filtering works as expected.
When i try to download the filtered dataset, i would expect to be able to download it, the same way as when i hand draw the polygon filter without using the polygon layer.

## Actual Behavior
When i try to download the filtered dataset then i get the error message from the image attached.
If i filter the point layer by a polygon that i hand draw, to be explicit, without the use of the polygon layer that i created manually,then i can export the filtered dataset without any problem

![download_failed](https://user-images.githubusercontent.com/46939331/184875959-39720ddb-4230-4952-81ae-11a0dd1952df.png)

Download all the points from the points layer, which intersect the polygon that i am drawing myself during the filtering -> Works!
Download all the points from the points layer, which intersect the polygon that is in the polygon layer - > Does not work.

## Steps to Reproduce the Problem

  1.Get a point layer
  2.Get a polygon layer
  3.Intersect the point layer by the polygon layer
  4. Try to download the filtered dataset. 

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform:Linux
  - Additional details:

---

@marthamareal commented on [Mon Sep 05 2022](https://github.com/GeoNode/geonode/issues/9856#issuecomment-1236905242)

This error is similar to the one raised when you try to export a map layer with the `Layer filter` option enabled.
**Steps to reproduce**:
- Open a map with a dataset
- Select a layer and apply filters and save
![b](https://user-images.githubusercontent.com/20810749/188442745-efe3da8a-7ad4-4044-a4c0-9602e3ee525d.png)
- Export the layer with both options enabled, and the error will be raised
![b2](https://user-images.githubusercontent.com/20810749/188442786-139b3d39-cefa-405f-84c8-f0215d0def24.png)

![b3](https://user-images.githubusercontent.com/20810749/188443210-2768aa12-42df-460b-b0b1-edf0a1b2166f.png)

**NOTE: Export works fine if `Layer filter ` is not enabled**

**Comment by DavidQuartz** [comment]
Can you provide some datasets to test with @giohappy ?

**Comment by giohappy** [comment]
@DavidQuartz I've created [this map](https://master.demo.geonode.org/catalogue/#/map/1893) where `ProvCM01012019_g_WGS84_lKHiGZ3` layer is filtered (`intersects`) by the upper layer.
If you try the export of `ProvCM01012019_g_WGS84_lKHiGZ3` you will get the error.

![image](https://user-images.githubusercontent.com/571129/190990679-398f575d-cc84-49a0-bc25-4633384a66b0.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 https://master.demo.geonode.org/geoserver/schemas/ows/1.1.0/owsAll.xsd">
   <ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>Could not parse XML request.
The element type "wps:ComplexData" must be terminated by the matching end-tag "</wps:ComplexData>"..</ows:ExceptionText>
   </ows:Exception>
</ows:ExceptionReport>
```

**Comment by DavidQuartz** [comment]
@giohappy this issue stems from Mapstore. The XML for the filter applied is wrongly constructed. I was unable to replicate it on Mapstore however because of [this issue](https://github.com/geosolutions-it/MapStore2/issues/8595)

**Comment by DavidQuartz** [comment]
@giohappy the corresponding issue has been created on Mapstore [here](https://github.com/geosolutions-it/MapStore2/issues/8603)
