### ISSUE TITLE
Several js files in 4.x branch have merge conflict markers

### ISSUE THREAD

**Issue by jraisane** [GeoNode/geonode-mapstore-client#1202]
In the 4.x branch, several js files like https://raw.githubusercontent.com/GeoNode/geonode-mapstore-client/4.x/geonode_mapstore_client/static/mapstore/dist/js/gn-home.js have cruft from an incomplete merge after merging this commit: https://github.com/GeoNode/geonode-mapstore-client/commit/fd2d9a0487522f71601ce56fc03dc9af9140d8c1

This is breaking geonode sites created from the geonode-project repo since they pull these files directly from the branch via the requirements.txt file. I've had to update my requirements.txt file to sync to 4.0.3 directly as a workaround.

**Comment by giohappy** [comment]
@jraisane the 4.x branch is dead. We're going to write it in the README. We have switched to 4.0.x, same as for GeoNode.

**Comment by jraisane** [comment]
Thanks, I see that the geonode-project repo has been updated to use the 4.0.x branch as well. I'll sync the changes.
