### ISSUE TITLE
Legend graphics will not render UTF-8 characters (eg. äöü)

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#122]
@gannebamm commented on [Thu Apr 08 2021](https://github.com/GeoNode/geonode/issues/7267)

## Expected Behavior

My style label will be rendered in the legend graphic.

## Actual Behavior

UTF-8 characters, like german Umlaute (üöä), will not render properly:

![grafik](https://user-images.githubusercontent.com/6172324/114062363-b8a16280-9897-11eb-9a8d-f4a144dcd76c.png)

## Steps to Reproduce the Problem

  1. create a style
  2. change the label to something with UTF-8 characters 'öäü'
  3. check the preview of the legend graphic

## Specifications

  - GeoNode version: 3.2 (master.demo.geonode.org)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
First thing to check @allyoucanmap is how the charset is managed when saving the style, since I can see wrong chars in Geoserver

![image](https://user-images.githubusercontent.com/571129/116112795-30ed8d80-a6b8-11eb-9071-4708f143d408.png)

**Comment by allyoucanmap** [comment]
@giohappy I did try with a standard MapStore and GeoServer locally and it legend was rendered correcly.
Could be the proxy endpoint `/gs/` used by the style editor in GeoNode that change the encoding?

**Comment by giohappy** [comment]
Ok, I'll move the issue back to GeoNode then.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode #7402](https://github.com/GeoNode/geonode/issues/7402) via [**ZenHub**](https://www.zenhub.com/)
