### ISSUE TITLE
Error on viewing info of a resource

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1238]
[screen-capture.webm](https://user-images.githubusercontent.com/20810749/194846031-f335f0a1-de68-4d84-a7a8-fa4c9df38a5b.webm)

![aa](https://user-images.githubusercontent.com/20810749/194845930-2fa5757e-ad94-4259-9a9b-c899b572076b.png)

**Comment by DavidQuartz** [comment]
@marthamareal can you please provide the link to the resource you are testing with? So far it works with the ones I have tried

**Comment by marthamareal** [comment]
https://development.demo.geonode.org/catalogue/#/dashboard/542
