### ISSUE TITLE
[GN 3.3.x] MapStore map view keeps spinning with error on Safari

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1244]
The map keeps spinning both in preview and full view. The console reports an error inside `gn-home.js`
Tested on Safari 13.1, 15.6.1 and 16.0

<img width="1680" alt="Screenshot 2022-10-14 at 13 49 22" src="https://user-images.githubusercontent.com/571129/195830360-de3eae63-ea2f-4d66-b62a-3c46020802df.png">

**Comment by giohappy** [comment]
@DavidQuartz can we do a time-boxed investigation and see if this is something solvable quickly?

**Comment by majid-saeed** [comment]
any update here?
