### ISSUE TITLE
Add 'executions' field to concrete instance endpoints

### ISSUE THREAD

**Issue by DavidQuartz** [GeoNode/geonode-mapstore-client#1245]
The client needs the execution information when doing requests to the endpoints for the concrete resources. 
This is needed to replace the resources/{pk}?include[]=executions request when the preview panel is shown, with requests to the concrete endpoints.

this for the second part of [this issue](https://github.com/geonode/geonode-mapstore-client/issues/1243)

**Comment by giohappy** [comment]
cllsing in favour of https://github.com/GeoNode/geonode/issues/10168
