### ISSUE TITLE
Dynamic rendering of document_detail view template

### ISSUE THREAD

**Issue by DavidQuartz** [GeoNode/geonode-mapstore-client#1246]
Allow the document_detail view/template to only render the body (without header and footer elements) instead of the whole page, based on a GET parameter which the client will provide in the request.
eg `documents/{pk}/document_detail?preview`

**Comment by giohappy** [comment]
@DavidQuartz the URL is `documents/{pk}/metadata_detail?preview` instead of `documents/{pk}/document_detail?preview`.
You can test it on branch https://github.com/GeoNode/geonode/tree/issue_1246

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode #10171](https://github.com/GeoNode/geonode/issues/10171) via [**Zenhub**](https://www.zenhub.com/)
