### ISSUE TITLE
Provide option to create mutual exclusive layers

### ISSUE THREAD

**Issue by MarkusKonk** [GeoNode/geonode-mapstore-client#1265]
If a LayerGroup contains several layers, it might happen that some of the layers should not be visible in combination with the other layers of the same group (and layers in the sub-group). Creators of a layer should be able to configure it in a way that that it is "mutual exclusive".
 
<img src="https://user-images.githubusercontent.com/2863409/198019365-3c3e673a-74dc-4a77-891f-162c0b15a28c.png" width=30% height=30%>

This means that if a user clicks on the layer to make it visible, the other layers are made invisible automaically.
There are two options to implement this feature:
Option 1 (preferred): Since this is an optional configuration for layer creators, this might be a good enhancement of the core.
Option 2: Implement a plugin to extend the TOC component.

**Comment by gannebamm** [comment]
@giohappy @allyoucanmap please take a look at the options

**Comment by giohappy** [comment]
@MarkusKonk @gannebamm here I guess you want a configuration at the group level (not per layer) to make the nodes under the group mutually exclusive. Something typical in many tree components, including the TOC in QGIS. Is it right?

This is something that will probably need to touch the core, and should itself be implemented inside the core. I don't think a plugin would be enough. I anticipate that it won't probably be that easy, but I think working with/inside the core is the way to go.

**Comment by gannebamm** [comment]
@giohappy yes on a group level. @MarkusKonk please give some insight about the current state of this task.

**Comment by MarkusKonk** [comment]
We made some progress regarding this issue as discussed with @gannebamm. However, we had to make some more or less minor changes to the MapStore2 and Client core.
- you can find the plugin [here](https://github.com/Thuenen-52North-Erweiterung-GeoNode/geonode-mapstore-client/blob/thuenen_exclusiveLayer/geonode_mapstore_client/client/js/plugins/ExclusiveLayer.jsx).
- we added an exclusiveLayer property to the [LayerUtils](https://github.com/Thuenen-52North-Erweiterung-GeoNode/MapStore2/blob/42ea47ffeb051151a8589790c81a69ddd4f06148/web/client/utils/LayersUtils.js#L466) and [MapUtils](https://github.com/Thuenen-52North-Erweiterung-GeoNode/MapStore2/blob/42ea47ffeb051151a8589790c81a69ddd4f06148/web/client/utils/MapUtils.js#L474) component.
- The dropdown for making a layergroup exclusive/non-exclusive is implemented in the [GeneralSettings component](https://github.com/Thuenen-52North-Erweiterung-GeoNode/geonode-mapstore-client/blob/31a93a640a68c27dadd9602016b1bc7f3ae327ee/geonode_mapstore_client/client/js/plugins/layersettings/GeneralSettings.jsx#L185). (I just noticed that we forgot to add internationalisation, still to be done.)
-

**Comment by allyoucanmap** [comment]
@tdipisa @giohappy next mapstore version 2024.01.00 will include the mutually exclusive groups so as soon as we align the MapStore submodule to 2024.01.xx we will get this feature.

see here the behavoiur on MapStore

https://github.com/geosolutions-it/MapStore2/assets/19175505/af2d90ea-df90-4b4b-8dc5-c830404b6fe1

**Comment by allyoucanmap** [comment]
> @allyoucanmap it seems the option is always available to the map user. Is this also a configuration option the person who creates that map -- at least to choose what is the default for a layer? The intention I have in mind is, that the map creator may want to visualize the layers in one group mutual exclusive, while not exclusive for another group.

@ridoo We introduced an options to group level called `nodesMutuallyExclusive` that is included in the map configuration so after saving it the state is presisted.  if nodesMutuallyExclusive is true all the children nodes at the first level will become mutually exclusive and they will change the icon to a radio button style, some examples:

here new york is mutually exclusive while other are normal groups

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/96db654c-e7bd-45a5-921f-f4a1fcea20b1)

you can have the exclusive group inside a nested group, here annotation group is mutually exclusive

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/333da1ca-8575-42f7-bb90-2cfd00e19e4c)

this option can be activated to a specific group level and in this other example you can see that the new your group is mutually exclusive while the nested annotation group is normal. As you can see the context menu allows you to change a specific group at any level

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/8785660c-6572-4da2-8751-4b8d2699975e)

**Comment by gannebamm** [comment]
@allyoucanmap I think the upstream implementation follows the same logic as ours. You can take a look at it here: https://geonode-demo.thuenen.de/catalogue/#/map/24

Each group (or subgroup) can be set as mutually exclusive. We also changed the button from 'eye' to 'radio button'. The state is saved.

**Comment by allyoucanmap** [comment]
> @allyoucanmap I think the upstream implementation follows the same logic as ours. You can take a look at it here: https://geonode-demo.thuenen.de/catalogue/#/map/24

@gannebamm I tried to import the map you shared in the latest mapstore version. The logic of mutally exclusive applies to all the first children including groups, like this one

https://github.com/GeoNode/geonode-mapstore-client/assets/19175505/b3143c2e-f378-4726-adc8-7f129800c889

**Comment by gannebamm** [comment]
> next mapstore version 2024.01.00 will include the mutually exclusive groups so as soon as we align the MapStore submodule to 2024.01.xx we will get this feature.

Took me a while to understand that right-click is now an option 🚀 

This seems to work quite well and is saved as state for the group. See working demo here: https://development.demo.geonode.org/catalogue/#/map/593

I think we can close this.

**Comment by ridoo** [comment]
I feel free to close this one then
