### ISSUE TITLE
Advanced Map Editor button should not be visible on GeoStory

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#1274]
Steps to reproduce:

- create a new geostory
- change media source of the cover
- select a map from the resource list and apply it
- edit map configuration

Expected result:

advanced map editor button should not be visible

![image](https://user-images.githubusercontent.com/19175505/199044243-e8fa9f96-085b-4975-b5ee-dd6a86be17bc.png)

Current result:

advanced map editor button is visible and it is not working

![image](https://user-images.githubusercontent.com/19175505/199044016-ceb875fc-96b8-4662-89ce-f916f46f42c5.png)

**Comment by giohappy** [comment]
fixed in https://github.com/geosolutions-it/MapStore2/issues/8761
