### ISSUE TITLE
Unable to upload GEOJSON files with .json extention

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1305]
The user should be able to upload .geojson and .json files in dataset form

Additional info:
This looks like an issue with the FE. if the file is saved as geojson instead of json, the upload workflow works as expected.
The issue is that in the request the base_file is sent as "undefined" if is json

**Comment by DavidQuartz** [comment]
@marthamareal can you provide some files to test with?

**Comment by marthamareal** [comment]
@DavidQuartz I can not upload a json file here but you can use an available dataset  and export GEOJSON to get the file.
