### ISSUE TITLE
Manage permissions on group not respected

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1307]
### Expected
When manage permission is given to the group (registered members inclusive), users should be able to edit permissions.
### Actual behavior
Users are unable to add/update/remove permissions.

Steps to reproduce:
1. create a map as an admin
2. assign registered members manage perm, and anyone = None
3. login as another member, view map and click on share
4. Notice that the manage form is not shown and user has change_resourcebase_permissions perm here https://development.demo.geonode.org/api/v2/resources/{id}

**Comment by giohappy** [comment]
@DavidQuartz the client should decide whether to show the share options based on the `change_resourcebase_permissions`, right? Can you please double-check what's happening here?
