### ISSUE TITLE
HTML tags in the title on pressing enter from the edit info form

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#1309]
Current behavior:
When you press enter in the title input on the information form, html tags are added to the title.

Steps to replicate:
1. Select and view a resource
2. Click on info
3. click on the title input and press enter.
4. Notice that html tags are added and can be saved on saving changes

**Comment by DavidQuartz** [comment]
@giohappy is it ok if we keep resource titles are plain text instead of allowing text formatting?
