### ISSUE TITLE
Upgrade MapStore

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1319]
The upgrade is needed to support new features in the client, and backport several improvements from MapStore.
This will target `master` and `4.1.x` branches.

**Comment by giohappy** [comment]
Let's hear from @allyoucanmap. Ideally we want to bring in the most and be aligned the most as possible to be ready to integrate new features like 3D.

**Comment by allyoucanmap** [comment]
@DavidQuartz @giohappy let's start from 2022.02.xx, then we will need also to make some test directly with master

**Comment by DavidQuartz** [comment]
Got it @allyoucanmap
