### ISSUE TITLE
Refactor how resource permissions are set inside the mapstore client context

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#135]
Currently GeoNode returns the permissions in multiple ways:

- layer viewer: returns an empty `__GEONODE_CONFIG__.permissionsList`. The client is using `resourceConfig.map.info` instead
- map viewer : same as layer map
- geostory viewer: apparently it returns all the existing Django permissions strings inside `__GEONODE_CONFIG__.permissionsList` (and strangley it also returns add_resourcebase see https://github.com/geosolutions-it/nexus-geonode/issues/84)

1 - The `permissionsList` property will be renamed to `perms`, to make it consistent with the new API (see https://github.com/geosolutions-it/nexus-geonode/issues/83).
2 - Remove permission related properties (`canEdit`, `canDelete`, etc.) from `resourceConfig.map.info`

**Comment by marthamareal** [comment]
For layers, `View Layer` loads the [new map view](https://github.com/GeoNode/geonode/blob/master/geonode/maps/views.py#L700) and at this point, the map object returned is a new instance with no permissions set on it. 

Suggestion to solve this are.
1. Have another view that will be used on `view layer`.
2. Use the layer name provided in the params on the `new_map` view  when its loaded from the `View Layer` button (eg https://master.demo.geonode.org/maps/new?layer=geonode:malawi_national_poverty_levels0&view=True#/)to get the permissions a user has on the layer and return those in the __GEONODE_CONFIG__.perms.

What do you think @giohappy @afabiani @allyoucanmap

**Comment by giohappy** [comment]
@allyoucanmap I guess that implementing a new "view layer" template / hookset will take some time on your side, isn't it? I see that you're managing the "is_new" / "is_new_resource" to drive the geonode config for the "new map" template. Will creating a new dedicated view require substantial work on the client side?

In this case I'd go for option 2 for the moment.

**Comment by allyoucanmap** [comment]
> I guess that implementing a new "view layer" template / hookset will take some time on your side, isn't it? I see that you're managing the "is_new" / "is_new_resource" to drive the geonode config for the "new map" template. Will creating a new dedicated view require substantial work on the client side?

I'm trying to list the needed actions to add the **view layer template**
- the layer view should use this [template](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/geonode-mapstore-client/layer_view.html) that use as base template the [map_edit.html](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/geonode-mapstore-client/map_edit.html) so there are not changes on this part
- remove the template from the map new hookset https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L156-L157
- restore the layer view hookset using the correct template https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L106-L110

Note: I'm seeing in the hookset of geonode-mapstore client also a commented **layer_edit_template** and some different behaviours between the **edit data** and **edit style** template. The edit data template is inside the map new hookset while the edit style template is its own hookset

> Use the layer name provided in the params on the new_map view when its loaded from the View Layer button (eg https://master.demo.geonode.org/maps/new?layer=geonode:malawi_national_poverty_levels0&view=True#/)to get the permissions a user has on the layer and return those in the GEONODE_CONFIG.perms.

About option is this a request client or server side?

**Comment by giohappy** [comment]
> About option is this a request client or server side?

Option 2 is server-side. @marthamareal how long it will take to make this change? I guess it would be quickier then option 1, right?

**Comment by marthamareal** [comment]
yes, option2 is much quicker and will take few hours to implement and test

**Comment by giohappy** [comment]
ok let's go for it @marthamareal
