### ISSUE TITLE
Backport of PR 1317

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1361]
To be backported both on 4.0.x and 4.1.x

**Comment by etj** [comment]
https://github.com/GeoNode/geonode-mapstore-client/pull/1317

**Comment by allyoucanmap** [comment]
@etj backported
- 4.0.x 254001e88048b534810073f8b56d64f0a8b542f5
- 4.1.x e757305ed1bcfbdcc35beb8a5be07bab536bf4ba
