### ISSUE TITLE
Export service selection should be hidden

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1386]
The recent version upgrade of MapStore [brought in a new feature](https://github.com/geosolutions-it/MapStore2/pull/8607) inside the dataset export windows, which is the option to select which service to use for downloading the data.

![image](https://user-images.githubusercontent.com/571129/217857866-0b36a250-5df7-4a18-976c-6d3c00090fc2.png)

WPS downloads were implemented to avoid using downloads over WFS, which are detrimental for Geoserver. In the case of very big datasets, it can be a huge load, both for Geoserver and the DB store.

Moreover, this option is meaningless to most part of users, and for the reason above, the WFS option should never be selected.

Unfortunately, MapStore doesn't expose a configuration to hide the option. 
An improvement is needed on its side to hide it from the GeoNode client.

**Comment by allyoucanmap** [comment]
depend on https://github.com/geosolutions-it/MapStore2/issues/8959
