### ISSUE TITLE
metadata fields labels are not translated inside the detail sidebar

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode-mapstore-client#1399]
The field labels are in the wrong localization (in the screenshot they should be in Italian):

![image](https://user-images.githubusercontent.com/717359/228518521-486365a2-dbe2-40d8-9965-939406bde38b.png)

Error spotted in a 4.0x

**Comment by giohappy** [comment]
@dsuren1 we should use the labelId (for the translation) instead of the label itself here:

https://github.com/GeoNode/geonode-mapstore-client/blob/57832d0ec883bf764dc3cbadcd0b46e2db960057/geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx#L7-L15
