### ISSUE TITLE
Wrong date fields mapping in info panel

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1423]
The metadata date field is shown with the static label "Published" inside the info panel, without taking into account the date type (creation, publication, revision). It's also placed in between two dates that are not related to metadata information (Created and Last modified) nut are managed by GeoNode instead.

The fix is to map the label for the metadata date to the selected value, and place it above the other dates.
Translations of the automatic dates should clarify that they're are dates unrelated to metadata.

**Comment by gannebamm** [comment]
Is fixed
![grafik](https://github.com/GeoNode/geonode-mapstore-client/assets/6172324/a2929355-19fc-40d9-b5f8-55cfafcf553e)
