### ISSUE TITLE
Implement date filtering

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1447]
This feature wasn't ported from GeoNode 3. We want to restore the ability to filter by `resource.date`.

- The filter will be placed above the spatial filter widget.
- It must contain a start and end date filter. I would keep it simple, leaving time out. 
- The filtering will be `<filter.startdate>T00:00:00 =< resource.date < <filter.enddate>T00:00:00`

Here below is the filter on GeoNode 3:

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/7ad3b7fe-2077-47e6-95db-b49563fb883c)

**Comment by allyoucanmap** [comment]
API v2 filters:
`/api/v2/resources?filter{date.gte}=2023-05-22T00:00:00&filter{date.lt}=2023-05-22T00:00:00`
`/api/v2/resources?filter{date.gte}=2023-05-22T00:00:00`
`/api/v2/resources?filter{date.lt}=2023-05-22T00:00:00`
