### ISSUE TITLE
Make the default catalogue view layout configurable

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1451]
There are cases where the list view is preferred over the grid view. 
We need a way to configure the default view layout (grid or list) from settings.

**Comment by giohappy** [comment]
@allyoucanmap how much would it take to have this configurable?

**Comment by giohappy** [comment]
@dsuren1 how hard would backporting to 4.1.1 be?
Please report here the localConfig settings that control this.

**Comment by dsuren1** [comment]
Btw, @giohappy the configuration prop to configure layout is `defaultCardLayoutStyle`
