### ISSUE TITLE
Implement Document creation from external URL

### ISSUE THREAD

**Issue by dsuren1** [GeoNode/geonode-mapstore-client#1477]
Documents can reference external URLs instead of local files.

The API already supports creating documents this way. You can see an example in the API usage examples, at the end of the paragraph [Resource Upload - 2.Document](https://docs.geonode.org/en/master/devel/api/usage/index.html#resource-upload).
It's a matter of putting the URL inside the payload's `doc_url` field **in place of** the files upload.

Requirements:
- The UI for document uploads will be extended with the "Add URL..." option. When clicked an input field will be shown at the end of the list of the other documents (if any) prepared for the upload
- The client will show a select box with the list of supported formats
- It will try to obtain the extension from the URL. It if cannot be obtained, or it doesn't match any valid format, the select box will be the empty value (default)
- The user will be asked to select a format before enabling the upload of the document

We will not check the validity of the URL, since it would be tricky because of CORS limitations, etc.

![image](https://github.com/geosolutions-it/C273-ISPRA-2023-UNEP-MAP/assets/571129/a6f1306a-c191-4569-824c-004d7ff30580)

**Comment by dsuren1** [comment]
@giohappy @allyoucanmap 

Kindly clarify these scenarios. Thanks

- Should the urls be always grouped and placed at the bottom of the files ? (Grouping by category looks clean IMO)
   <img width="325" alt="Screenshot 2023-06-22 at 6 20 43 PM" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/7d1447cf-1bab-4726-97d2-95f2d7f6da68">


- When user adds a duplicate url should we warn them with a helptext at the bottom of the duplicate entry or simply remove the entry like we do with files or should we allow duplicate entries too?
  <img width="307" alt="image" src="https://github.com/geosolutions-it/C273-ISPRA-2023-UNEP-MAP/assets/26929983/89caad67-5a6e-4487-80a2-d63b20f4fbfa">

- Can we use url as resource name, with files filenames are used but with url, two different urls can have same file name with extension so grouping with filename will not allow user to create a resource with same name. Title can be lengthy but the user can still modify the name after the resource is created. Your thoughts?

- When the extension is obtained from the url, is it okay to hide the extension's dropdown as it doesn't make sense to allow user to modify the extension again?

- This feature should be visible only on upload as document and not for dataset. Kindly correct me if I'm wrong

**Comment by giohappy** [comment]
>Should the urls be always grouped and placed at the bottom of the files ? (Grouping by category looks clean IMO)

Well, in general, I prefer when the UI respects the order of actions. If you have added multiple things it's easier to track them when they're sorted in order. 
BTW I don't think it's a big problem if it's easier (and nice looking) to group them. It won't be such a frequent case for users to add multiple files and URLs together....

>When user adds a duplicate url should we warn them with a helptext at the bottom of the duplicate entry or simply remove the entry like we do with files or should we allow duplicate entries too?

A message is preferable, otherwise, it will be hard for the user to understand what's happening. If we have duplicates  we set the Upload disabled user doesn't correct those URLs

> Can we use url as resource name, with files filenames are used but with url, two different urls can have same file name with extension so grouping with filename will not allow user to create a resource with same name. Title can be lengthy but the user can still modify the name after the resource is created. Your thoughts?

What happens if you try to send the same URL twice to the API? I expected it to manage the name conflicts.

>When the extension is obtained from the url, is it okay to hide the extension's dropdown as it doesn't make sense to allow user to modify the extension again?

Rather than hiding, I would disable the select box and show the detected extension.
One note about the UI: Can we make the dropdown smaller and with a style more similar to the extension label that we show for file uploads?

>This feature should be visible only on upload as document and not for dataset. Kindly correct me if I'm wrong

Correct, only for documents

**Comment by dsuren1** [comment]
@giohappy 
> What happens if you try to send the same URL twice to the API? I expected it to manage the name conflicts.

Able to create the resource when sending same URL twice via separate call to API

**Comment by dsuren1** [comment]
@giohappy 
So I guess we don't need to show error when same url is added

**Comment by giohappy** [comment]
>So I guess we don't need to show error when same url is added
@dsuren1 I wouldn't care...
