### ISSUE TITLE
Use all the available height for the abstract in a card

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1482]
The abstract text is limited to the first row inside the resource card, when it could wrap multiple lines taking advantage of the available height above the buttons.

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/af24a1e8-1c39-4db9-ab3f-2a464709de81)

**Comment by giohappy** [comment]
If it doesn't take to much it would be great to have it in 4.1.1 @dsuren1

**Comment by dsuren1** [comment]
@giohappy Sure 👍. I think this shouldn't take much time
