### ISSUE TITLE
The download spatial filter doesn't work with Geoserver 2.23.0

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1519]
Due to a bug with the WPS Download extension for Geoserver, JSON geometries are not parsed anymore (see https://osgeo-org.atlassian.net/browse/GEOS-11071).
This can be solved client-side by converting the ROI geometry to WKT. We will implement the solution on top of MapStore [2022.02.xx](https://github.com/geosolutions-it/mapstore2/tree/2022.02.xx), since it hasn't been implemented in MapStore master yet.

**Comment by dsuren1** [comment]
Upstream [PR](https://github.com/geosolutions-it/MapStore2/pull/9342)
