### ISSUE TITLE
Implement a UI component to trigger asynchronous operations on a resource

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1559]
### Introduction
We want to replace the following legacy forms:

- "upload style"
- "upload metadata"

end restore the "replace" operation for datasets and documents, which wasn't ported from GN 3.

All these operations should provide a similar UI to configure, execute, and monitor the execution of an operation.

### State and behavior
All these operations are asynchronous and blocking:

 - **asynchronous**: the operation will use the `executions requests` endpoint to obtain the status of the operation, similar to the current upload operation
 - **blocking**: the resource cannot be edited while the operation is running. Only editing operations should be blocked, while view-only interfaces will be allowed (embed, preview).

This kind of operation falls inside the lower right quadrant of the following matrix:

|   | Sync | Async |
| ------------- | ------------- | ----- |
| Non-Blocking |    | |
| Blocking   |    | X |

### UI

The component will show in a modal window with a minimal design. In general, it encompasses 4 states:

1. File selection
2. Ready to execute
3. In progress
4. Completed

Being a blocking operation, the modal cannot be closed until the operation is completed or canceled.
When the resource viewer is opened the client will check the execution request obtained from the REST API response for the resource. If there's an ongoing operation for the resource, the blocking modal for the specific operation will be shown.

State 1
![execute_1](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/48bf76ee-db82-4101-b3a7-4367e943f4bc)

State 2
![execute_2](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/71846258-f836-46ac-a142-91dbaa66e75b)

State 3
![execute_3](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/93830b59-bb85-4a8e-905f-4b47c5a0a828)

State 4
![execute_4](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/a61d3fe8-2dea-4052-b90c-ea77cfd55276)

### Implementation notes
The component can be used inside any page of the GeoNode client. For the moment it will be adopted inside detail pages, but in the future, we could adopt it also for operations on the catalog.

**Comment by dsuren1** [comment]
> Users can close and reopen the modal window without losing the state of the operation.

Upon closing the modal, the execution state is to be captured in a separate modal (like export data) allowing user to perform a new upload action.
<kbd>
<img width="603" alt="image" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/2d8233d2-8985-427c-be9a-ef11ae4fdd51">
</kbd>
Any manner of error during the upload process is expected to be handled by the backend. The error is shown as an info icon with a tooltip next to file as shown in the screenshot above.

@giohappy Kindly correct me if I'm missing something from our last discussion on this issue

**Comment by giohappy** [comment]
Resurrecting this old analysis.

> @giohappy Kindly correct me if I'm missing something from our last discussion on this issue

I think you're correct.

**Comment by giohappy** [comment]
@allyoucanmap I have edited the description on the base of our call.
