### ISSUE TITLE
Image Feature is not visible on the GFI 

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode-mapstore-client#1576]
## Expected Behavior
If one of the layer attribute is set as image i should be able to see the image

## Describe the bug
The image link is broken
![fe_issue](https://github.com/GeoNode/geonode-mapstore-client/assets/51856725/622bb113-d9f2-4377-9561-4aafe1119365)

The image SRC looks empty:

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/51856725/23645c46-0894-44b5-ac17-aef80b31668e)

## Steps to Reproduce the Problem

  1. Navigate to this link https://development.demo.geonode.org/catalogue/#/dataset/53
  2. Click on the red dot
  3. The image is broken

## Specifications

  - GeoNode client version:
  - Browser:
  - Installation type (vanilla, geonode-project):
  - Additional details:

**Comment by giohappy** [comment]
@mattiagiupponi feature templates are generated by GeoNode. We should take a look at them and see why the src attribute is broken.

**Comment by dsuren1** [comment]
Upstream issue: https://github.com/GeoNode/geonode/issues/11601

**Comment by dsuren1** [comment]
Fix: https://github.com/GeoNode/geonode/pull/11602

**Comment by giohappy** [comment]
closed in favour of https://github.com/GeoNode/geonode/issues/11601
