### ISSUE TITLE
Adopt the new download_urls array property

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1587]
Since https://github.com/GeoNode/geonode/issues/11421 the resource API endpoints return a new array property for the download URL:

```
 "download_urls": [
   {
      "URL": .... , 
      "ajax_safe": true|false, 
      "default":true|false
   },
]
```

It's array in view of supporting multiple download URLs. At the moment only one value is returned, with the `default` property set to true.

The relevant addition is the `ajax_safe` property. This value tells the client if the download URL can be called with AJAX or if an href should be used instead. This information is important for specific downloads that do not use the GeoNode backend but use instead external URLs that might not support CORS.

**Comment by giohappy** [comment]
@ridoo at the moment it uses a simple heuristic:

- datasets: if they're not provided by a custom `Link` they're considered AJAX safe, since they're served by GeoNode's Geoserver WPS service (see [here](https://github.com/GeoNode/geonode/blob/master/geonode/layers/download_handler.py#L66))
- documents: if they're local document (not served from an external URL) they're considered AJAX safe (see [here](https://github.com/GeoNode/geonode/blob/master/geonode/documents/models.py#L105))

this logic is reflected inside the output [generated by the serializer](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/serializers.py#L295-L315).

A custom download handler for datasets can override the `DatasetDownloadHandler.is_ajax_safe()` method to implement a different logic.

**Comment by ridoo** [comment]
Thanks for your feedback and the pointers!

So the intention seems to be avoid using a proxy for download links linking to (maybe) CORS disabled backends, as you do not want big datasets to be looped through the GeoNode backend.
