### ISSUE TITLE
In edit mode, custom font added to Geostory occurs twice in editor

### ISSUE THREAD

**Issue by dsuren1** [GeoNode/geonode-mapstore-client#1593]
## Describe the bug
In edit mode, custom font added to Geostory plugin occurs twice in editor

## Expected Behavior
In edit mode, custom font added to geostory should not occurs twice in editor

## Steps to Reproduce the Problem

  1. Add custom font families to Geostory plugin
  2. Open a geostory with write access, and open a text editor check the fonts list

## Specifications

  - GeoNode client version:
  - Browser:
  - Installation type (vanilla, geonode-project):
  - Additional details:

**Comment by mumairr** [comment]
@giohappy had a meeting with @dsuren1 and eventually able to replicate the issue. Looking at the possible issue in code

**Comment by mumairr** [comment]
Created a PR for the issue fix on MS master.
Problem was non reproducible on Mapstore and occured only on GN MapStore Client.
A generic fix was possible thanks to @allyoucanmap
