### ISSUE TITLE
No option to view detail of a layer from the map view

### ISSUE THREAD

**Issue by ahmdthr** [GeoNode/geonode-mapstore-client#1660]
Problem: When I, as a viewer, look at a map with multiple data layers, I do not get detailed information about the layers used in the map without leaving it. So far I can look at the map, but this jumps to the respective data set and the map is left. is exited.

![267068618-074e18fc-4ebb-41c1-a8fe-6df75c0fecb4](https://github.com/GeoNode/geonode-mapstore-client/assets/116570171/82a9a9ca-72a0-44bb-af25-06b1e68181d9)

Objective: As a viewer, I would like to be able to display the detail panel of the layer on the right-hand side via an additional layer on the right side. For this I do not leave the map view. A mockup is shown in the following figure.

![267068772-3456e3c9-858d-426f-9db6-4f76a0648b97](https://github.com/GeoNode/geonode-mapstore-client/assets/116570171/035219e2-e095-4fd4-8680-3f176786214a)

**Comment by ridoo** [comment]
There is an existing issue for this: #1616

**Comment by giohappy** [comment]
closing in favor of #1616
