### ISSUE TITLE
List the fields required from resource responses

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1707]
### Introduction
When calling the resources APIs all the resource fields, and related fields, are returned inside the response. 
The client also asks for additional information (like, execution requests status to visualize any running execution) adding further load and size to the API response.

[Now we have the option](https://github.com/GeoNode/geonode/pull/12094) to selectively exclude/include the fields we want in the response, and we can limit what we want in the response to what is needed for the client functionality.

The basic solution is to add `exclude[]=*` to first remove all fields from the response, and then include the required fields one by one by adding `include[]={the_field}`.
As an example, we could obtain the pk and the title only with `/api/v2/resources?exclude[]=*&include[]=pk&include[]=title`.

This can become really verbose, and it steals characters from the max length of `GET` parameters we can send in a request.
For this reason, we have planning to implement the concept of `profiles` (see https://github.com/GeoNode/geonode/issues/12104). They will let the client query the API for a given profile which will return a pre-configured set of fields. Profiles will be configurable in GeoNode settings, so we can tweak and customize them easily.
It will be something like `/api/v2/resources?includeprofile[]=basic`, where `basic` might include only pk, title and abstract (for example).
Of course, profiles will still support asking further fields along those pre-configured for the specific profile.

Selective inclusion of fields and `profiles` give us great flexibility to fine-tune and optimize requests.

### Task
For the purpose of configuring a set of profiles for the client we need to list of fields that the client needs to drive its functionality:

 - catalog listing
 - catalog preview panel
 - viewers
 - editors
 - (else)

For each request that the client currently does the list of fields must be listed, including any extra fields (like executions, linked resources, etc.).

**Comment by giohappy** [comment]
>Clone feature still requires whole resource object

@dsuren1 couldn't Clone make a further request to obtain the required information?

**Comment by dsuren1** [comment]
Yes, at the time of making clone, we can request for the whole resource to be used for cloning
