### ISSUE TITLE
Adapt the client to the new output information from the execution requests for uploads

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1748]
The output params of the execution requests for uploads will be changed to include the ID of the new resource (https://github.com/GeoNode/geonode-importer/issues/240).

The client must bi adapted to handle the new output.

**Comment by mattiagiupponi** [comment]
branch for test is available. PR is here https://github.com/GeoNode/geonode-importer/issues/240

**Comment by giohappy** [comment]
@dsuren1 there's a regression. Contrary to the previous behavior, the button shows a generic "View datasets" instead of "View" (linking to the specific resource) even if only one resource has been uploaded.

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/21f23670-bc55-47bb-b238-209f0b033068)

**Comment by dsuren1** [comment]
@giohappy 
Reason being is that the recent changes done on the client side is not reflected in dev.demo
<img width="342" alt="image" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/2c89b71c-967c-4030-9329-db61ffd83e2f">

**Comment by giohappy** [comment]
@dsuren1 right, the PR with the new bundle wasn't merged. It is working now.
