### ISSUE TITLE
Request to rest/geostore in latest version when loading dashboard

### ISSUE THREAD

**Issue by pchevali** [GeoNode/geonode-mapstore-client#1781]
## Describe the bug

When loading a dashboard created in version 4.1 in the latest 4.3 version there is a request to the folowing path, it results in 404 :
/rest/geostore/resources/resource/[pk]/attributes

## Expected Behavior

The request should be routed to the geonode api

## Steps to Reproduce the Problem

  1. Open an existing dashboar
  2. Open debug tools
  3. Look for 404 on attributes

## Specifications

  - GeoNode client version: branch 4.3.x
  - Browser: firefox
  - Installation type (vanilla, geonode-project): Geonode project
  - Additional details:

**Comment by pchevali** [comment]
In the console the error seems to come from : storeDetailsInfoDashboardEpic 
At this place in the [code](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/epics/config.js#L231)
It seems to be linked to the DetailsPanel change from mapstore :

https://github.com/geosolutions-it/MapStore2/commit/d40233dd4e5782603ecc545a2b1644aaa674a9e6

**Comment by pchevali** [comment]
The error is also present on [stable.geonode.org](https://stable.demo.geonode.org/catalogue/#/dashboard/9843)

![image](https://github.com/GeoNode/geonode-mapstore-client/assets/1221917/11cf2666-97a5-49f3-8047-f7356a7976f3)

**Comment by johnpaul89** [comment]
Hey @pchevali @frafra , were you able to solve this or find a work around? I also have this bug in my geonode.

**Comment by allyoucanmap** [comment]
@pchevali @johnpaul89 here the PR with the fix to remove the error in console https://github.com/GeoNode/geonode-mapstore-client/pull/1814

**Comment by giohappy** [comment]
Backport needed
