### ISSUE TITLE
Dashboard doesn't have any CSW catalog

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode-mapstore-client#1784]
## Describe the bug
When opening a dashboard, no defaut CSW catalog are shown

https://github.com/GeoNode/geonode-mapstore-client/assets/51856725/aee20d65-61e6-4f57-812a-cc75f29d81bc

## Expected Behavior

At least the geonode CSW catalog should be shown

## Steps to Reproduce the Problem

  1. Open a new dashoard
  2. add widget
  3. chart
  4. Click on the dropdown box

## Specifications

  - GeoNode client version: master/4.3.0
  - Browser: any
  - Installation type (vanilla, geonode-project): any
  - Additional details: None

## Quick FIX

The regression was introduced by this fix in GeoNode https://github.com/GeoNode/geonode/issues/12277 and https://github.com/GeoNode/geonode/pull/12278 
Two possible solutions
1) Re-adding the settings in the settings.py file in GeoNode patch the issue
2) Adding manually the CSW catalog by pressing on the `+` icon

## Possible long-term solutions

- Let the DashBoardEditor dont rely anymore on that particular config
- Re-add the configuration by changing the name, so it will be used by the Dashboard ONLY

CC @giohappy @allyoucanmap @ElenaGallo

**Comment by giohappy** [comment]
@allyoucanmap maybe it's related to the change in https://github.com/GeoNode/geonode-mapstore-client/pull/1777 where the catalogue has been removed?
