### ISSUE TITLE
Dashboard - Multiple charts UI bug

### ISSUE THREAD

**Issue by ElenaGallo** [GeoNode/geonode-mapstore-client#1785]
## Describe the bug
The UI for selecting the charts is not correct because it is too long and hides the button to modify/delete the widgets

When the dimensions of the widget are small, the button to modify is available but it is not possible to change the chart.

## Expected Behavior
You can always select charts and edit/delete charts on a chart widget

## Steps to Reproduce the Problem

https://github.com/GeoNode/geonode-mapstore-client/assets/56537133/84e21b0b-26a7-4f77-877a-e8de8dce887d

## Specifications

  - GeoNode client version: stable.demo
  - Browser:
  - Installation type (vanilla, geonode-project):
  - Additional details:

**Comment by pchevali** [comment]
Hi,
I guess that it's related to  #1782 .
Pull request #1783 solves it for me

**Comment by giohappy** [comment]
@dsuren1 please review the proposed fix from @pchevali and in case let's close this.

**Comment by dsuren1** [comment]
Closing in favor of #1782

**Comment by dsuren1** [comment]
Closing in favor of #1782
