### ISSUE TITLE
Wrong map zoom when creating a new map from layer is stored within the map state

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#1788]
We have a bug (that might be two) with the map extent when a new map i created from a layer.
Here it is what happened (see video below):

1. Create a new map from an existing layer
2. The map zooms correctly to the layer, but after a few moments it zooms to the whole globe (error 1)
3. If you switch back to the dataset the map is not zoomed to the layer. Whatever datasets you open the zoom is global, which appears to be a problem with a global map state (error 2)
4. If you refresh the page for the dataset the zoom is correct (map state is reset)

![map_extent_bug](https://github.com/GeoNode/geonode-mapstore-client/assets/571129/a85de623-ee9a-4495-855a-bdee3f15aace)

**Comment by allyoucanmap** [comment]
@giohappy here the PR https://github.com/GeoNode/geonode-mapstore-client/pull/1790

there is still a problem on a delay on the intial position of the map that should be solved by this other PR on MapStore https://github.com/geosolutions-it/MapStore2/pull/10449

As soon as the other PR on MapStore is merged we could also port the improvement on geonode-mapstore-client
