### ISSUE TITLE
Bump adapter Version to 1.0.7?

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-mapstore-client#18]
@afabiani  is it okay to bump version to 1.0.7 https://github.com/GeoNode/geonode-mapstore-client/blob/master/requirements.txt#L2 ?

**Comment by afabiani** [comment]
Fixed by https://github.com/GeoNode/geonode-mapstore-client/commit/73f045289aa24a3f2723bff61f929c8687170a09
