### ISSUE TITLE
Dashboard not loading on 4.3.x after upgrading from 4.1.3 rest/geostore/resources

### ISSUE THREAD

**Issue by johnpaul89** [GeoNode/geonode-mapstore-client#1812]
## Describe the bug
When creating a new dashboard or loading an existing dashboard, no widgets are visible once you save the data. The dashboard page remains empty even after creating and saving widgets. 

![image](https://github.com/user-attachments/assets/271255ac-535d-4656-829d-2f6cc4bd4ea6)

This bug is well visible after upgrading to version 4.3.x from version 4.1.3 . 

Pre existing dashboards do not load, or new dashboards do not load in the new version 4.3.x after updating. 

This bug can be tracked to this url **_/rest/geostore/resources/resource/{id}/attributes_** which gives a 404 error, NOT FOUND. 

![image](https://github.com/user-attachments/assets/9a4423d4-733c-4cd1-836b-c687dd9cd1b1)

## Expected Behavior
The expected behavior is that when I save and reload my page I should see my dashboard with all the widgets it has. 

## Steps to Reproduce the Problem

  1. Have a pre-existing geonode with geonode mapstore client instance running specifically 4.1.3
  2. Create a dashboard
  3. Update your existing instance to 4.3.x
  4. Try loading your created dashboard or create a new dashboard, save the page and then reload the page.

## Specifications

  - GeoNode client version: 4.3.x
  - Browser: Brave browser
  - Installation type (vanilla, geonode-project): docker, geonode-project
  - Additional details: The error might be caused by the gn-catalogue.js file etc

**Comment by allyoucanmap** [comment]
@johnpaul89 I currently not able to reproduce this issue, could you please confirm the version you are starting from, is it 4.1.3 or 4.3.1?
I'm not seeing the tag 4.1.3 so I'm wondering if the description of the issue is correct, thanks

**Comment by johnpaul89** [comment]
I was able to solve the issue. The issue was due to not matching ssl certificate keys from cloudflare to the ones on the docker image. I made both ssl certificate keys to match.

Thanks.
