### ISSUE TITLE
Infinite loading for dataset embed

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#1827]
## Describe the bug

Dataset embed page shows always an infinite loading spinner

## Expected Behavior

Dataset embed page should show the map viewer

## Steps to Reproduce the Problem

  1. Open the embed page of a dataset (eg. [maps/692/embed](https://development.demo.geonode.org/maps/{pk}/embed))

## Specifications

  - GeoNode client version:
  - Browser:
  - Installation type (vanilla, geonode-project):
  - Additional details:

**Comment by giohappy** [comment]
To be backproted
