### ISSUE TITLE
Dataset filtering option missing

### ISSUE THREAD

**Issue by obediobadiah** [GeoNode/geonode-mapstore-client#1913]
## Expected Behavior

When viewing a dataset under Geonode 4.1.x  there was a **FILTERING OPTION** to FILTER and SAVE the filtered dataset.

Like in the screenshot below:

<img width="1163" alt="Screenshot 2024-10-24 at 12 48 17 at night" src="https://github.com/user-attachments/assets/eef5f1bc-7711-4bcb-a0aa-3b588d978816">

## Actual Behavior

But after upgrading the version to 4.3.x, **FILTERING OPTION** is missing and we're no longer available to filter or to SAVE the filtered dataset.

Like in the screenshot below:

<img width="1680" alt="Screenshot 2024-10-24 at 12 55 32 at night" src="https://github.com/user-attachments/assets/db8678dc-84b5-4f65-9ce4-f37fc159a718">

PLEASE HELP ME HOW I CAN GET THAT FILTERING OPTION AND TO BE ABLE TO SAVE THE FILTERED DATA. THEN DOWNLOAD IT

## Steps to Reproduce the Problem

  1. On the Catalog
  2. Click on VIEW on one of the Dataset
  3.

## Specifications

  - GeoNode version: Geonode 4.3.x
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): Manual
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@dsuren1 the [configuration seems to be there](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/static/mapstore/configs/localConfig.json#L651-L654) but the FIlter button doesn't show up. Maybe something is wrong with the FilterPlugin?

**Comment by obediobadiah** [comment]
@giohappy as I checked the FilterLayer Plugin doens't exist. Yes the configuration is there but the Plugin file is not

**Comment by dsuren1** [comment]
PR addressing the issue is [here](https://github.com/GeoNode/geonode-mapstore-client/pull/1914)

> [!NOTE]
Menu options with respect to modification of the resource and grouped under `Resource`. And in order to save the dataset, `Resource -> Save`

**Comment by vidlb** [comment]
Hi @dsuren1 , from what I understand, this should be fixed in Geonode 4.4.1 ?  
But I'm still facing this issue, what are the steps in order to fix it in my geonode-project ?  
I'm manually updating files to align with the geonode-project repo, is it possible I missed something or should I wait for the next release ?

**Comment by dsuren1** [comment]
@vidlb 
You're correct. The fix was merged into the 4.4.x branch after 4.4.1 went live. It should be available in the next release.  
If you'd like to test it locally, you can refer to these  [changes](https://github.com/GeoNode/geonode-mapstore-client/pull/1924).

**Comment by giohappy** [comment]
hi @vidlb we don't have a date for 4.4.2 yet but it will be probably released in January.

**Comment by vidlb** [comment]
> @vidlb You're correct. The fix was merged into the 4.4.x branch after 4.4.1 went live. It should be available in the next release. If you'd like to test it locally, you can refer to these [changes](https://github.com/GeoNode/geonode-mapstore-client/pull/1924).

Thanks, but I don't understand how to proceed if I want to patch this file in my instance, is it even possible ? Or can I just pip install the package directly from the master branch in my container  ?

**Comment by vidlb** [comment]
Well I guess this is not possible, I just tried to update only mapstore from the master branch and I got JS errors.

**Comment by vijdz** [comment]
Hi @giohappy , still no release date for 4.4.2 ? It would be great to have a small bugfix release, since this issue is really incapacitating in some case (for my users : dataset is too large to be downloaded as it is, filtering is mandatory...)
