### ISSUE TITLE
Client - Map page doesn't work on geonode client

### ISSUE THREAD

**Issue by luorlandini** [GeoNode/geonode-mapstore-client#228]
On viewer page, the map doesn't load, get error page.

![Schermata 2021-06-08 alle 14 17 57](https://user-images.githubusercontent.com/4085786/121183787-b9894d00-c864-11eb-9a2a-9c5687fbd222.png)

**Comment by luorlandini** [comment]
@allyoucanmap 

the issue is related to the property default_map_backgrounds, missing in the state.

adding the conf like MS, that set some initialState, the page works 

```
 "initialState": {
	"defaultState": {
		"catalog": {
			"default": {
				.....
				"staticServices": {
					"default_map_backgrounds": {
						.....
					}
				}
			}
		}
	}
}
```

**Comment by allyoucanmap** [comment]
@luorlandini I think we should fix in mapstore because we don't use those settings
