### ISSUE TITLE
rest_framework namespace and duplicate URLs

### ISSUE THREAD

**Issue by asgharsir** [GeoNode/geonode-mapstore-client#344]
Issue started with seeing this:
![image](https://user-images.githubusercontent.com/47123144/126136561-88721ab8-197b-4402-b13d-dcda27e84a76.png)

This we see when we use geonode 3.2.x or 3.3.x, but this was not appearing while using the master. I investigated what is different in the master. I found that the issue is related to geonode-mapstore-client, and the genode master is installing the latest/recommended version while, geonode 3.2.x for example, is installing version 3.2.1 of django-geonode-mapstore-client.

But there is no fix in the recommended version also. `mapstore2_adapter` url patterns are part of app config, which is not working for the `mapstore/rest`. Those URLs are not there in master branch. In 3.2.x **there is an additional problem. The `mapstore/rest/` urls are all duplicated**:
![image](https://user-images.githubusercontent.com/47123144/126138543-a777b627-87e8-4fe4-8b1b-1f30a2a244dd.png)
Above we can see that all the urls are actually duplicate. This can expose to us, or already exposing to us, to unexpected bugs.

- Also, we could decide do we really need `rest_framework.urls`, in the first place? Because `mapstore-client` is supposed to be integrated into `geonode` apps which is already having this. But even if we needed it, a best practice could be to avoid this common name: `rest_framework`.
- But actually I changed this common name, and still there was the problem. Because that was not the cause of the problem.
- And in master branch although we are not having `namespace is not unique` warning anymore, but we are not having `mapstore/rest/` urls either.

### Actual Behaviour

- Apps using current versions of geonode are seeing: `?: (urls.W005) URL namespace 'rest_framework' isn't unique. You may not be able to reverse all URLs in this namespace`.
- There are duplicate `mapstore/rest` urls.
 
### Expected Behaviour
No violation of unique namespace, specially for our APIs.
No duplicate URLs.

I think the fix is not in not using the namespace, rather it is the realization of the problem. The solution is maybe in fixing the app's configuration module.

**Comment by giohappy** [comment]
@asgharsir it would be better if you fixed the issue on master branch and then assigned the backport 3.3.x and backport 3.2.x labels.
