### ISSUE TITLE
Add Plugins in Mapstore Client

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode-mapstore-client#37]
Good afternoon,

About geonode-mapstore-client:

I think it is necessary to have a more complete version of geonode-mapstore-client.

Integrate the following Plugins or functions:

.- Locate me
![image](https://user-images.githubusercontent.com/7094961/70377086-89c85480-1910-11ea-9027-11b6b3943305.png)

.- Feature Info
![image](https://user-images.githubusercontent.com/7094961/70377093-9a78ca80-1910-11ea-883b-213dc142e371.png)

Additionally solve:

.- The search service settings are not saved on the Map right now
![image](https://user-images.githubusercontent.com/7094961/70377100-b1b7b800-1910-11ea-948d-c39c6beedb1d.png)

.- And another useful issue to solve is the display of attribute results in versions for mobile devices.
![image](https://user-images.githubusercontent.com/7094961/70377125-183cd600-1911-11ea-80c4-5dfdd863debd.png)

It would be great if the deployment is achieved by displaying the attributes as in the official version of Mapstore. (on mobile devices)

![image](https://user-images.githubusercontent.com/7094961/70377175-84b7d500-1911-11ea-8c9d-135bb0e136c3.png)

If someone can guide how to do it or if it is designed for future updates.

Thanks for your attention

**Comment by gannebamm** [comment]
We need some documentation on how to develop for mapstore2 in geonode. I am still not sure how to get the sourcecode running side-by-side with a geonode deployment.

**Comment by gannebamm** [comment]
Just a little update. I currently try to get a working mapstore2 GeoNode dev environment and face some issues:
https://groups.google.com/forum/#!topic/mapstore-developers/q_C-5yZBSPE

I will post documentation as soon as I get the dev env working properly.
