### ISSUE TITLE
adding mapstore-client plugins 

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-mapstore-client#4]
Hi  I'm trying to add plugins such as add local vector files, and annotations to my mapstore client viewer. I try including the plugins code in the  **ms2_map_viewer_plugins.js** file and run collectstatic . but still nothing appears on the mapstore viewer. am I modifying the wrong file ?

( a similar issue was adressed in https://github.com/geosolutions-it/geonode-mapstore-client/issues/150 )

**Comment by gannebamm** [comment]
Any news here? I need to enable 'add Group' functionalities to MS2
