### ISSUE TITLE
slow PUT requests when opening a style for editing

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#41]
It takes a lot to load the style source of a CSS style for editing because of the followig **PUT** request (with CSS body as the payload) which is run right away at the beginning.

`https://master.demo.geonode.org/gs/rest/workspaces/geonode/styles.json?name=<uuid>_ms_1580897799071&access_token=<access_token>
`

The video below shows a session. It takes **more then 9 seconds** to load the style source in this case.

![style_edit](https://user-images.githubusercontent.com/571129/73833563-74857e80-480a-11ea-8c45-d257f3f40bf1.gif)

The video was done with [this layer on master demo](https://master.demo.geonode.org/layers/geonode_data:geonode:Reg01012019_g_WGS841)

**Comment by afabiani** [comment]
@giohappy I guess that should be fixed now. Not sure which was the issue exactly, latest MapStore updates and some cleanup of the calls seem to be fixed the issue.

Please try again and let me know,

**Comment by giohappy** [comment]
Unfortunately I still face slow PUTS @afabiani . I've pulled and upgraded requirements (django-mapstore-adapter==2.0.2 and django-geonode-mapstore-client==2.0.1) before recording the following video.

![put_style](https://user-images.githubusercontent.com/571129/76442529-61457000-63c1-11ea-83bf-522cd1dcd84d.gif)
