### ISSUE TITLE
Verify extensibility of Search plugin services configuration

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#420]
The Search plugin configurations of MapStore allows to add service to make nested query (eg first request name of road then house number) see https://github.com/geosolutions-it/MapStore2/issues/7182.

Needed actions:

- include fixes related to Search plugin nested services on branch 2021.02.xx of MapStore2
  - [x] https://github.com/geosolutions-it/MapStore2/issues/7182 
  - [x] https://github.com/geosolutions-it/MapStore2/issues/7201 
- update the MapStore2 submodule to branch 2021.02.xx for geonode-mapstore-client 3.3.x and master branches
- verify configurability of Search plugin in a custom geonode-project
- add documentation in the read me on how to extend the configuration for a plugin and link specific configuration of MapStore framework

**Comment by simboss** [comment]
@luorlandini can you work on this one as have time?

**Comment by luorlandini** [comment]
@simboss yes, sure

**Comment by luorlandini** [comment]
- verify configurability of Search plugin in a custom geonode-project
about this point, the Search plugin it is configurable in a custom geonode-project and works as expected

**Comment by simboss** [comment]
@luorlandini is this properly documented?

**Comment by luorlandini** [comment]
@simboss this activity is documented on the mapstore side, it written both for the javascript api, and in the developer guide, this is the PR under review 
https://github.com/geosolutions-it/MapStore2/pull/7202/files

about geonode mapstore client, there are some examples to modify and update the configuration, for master and 3.3.x branch:
https://github.com/GeoNode/geonode-mapstore-client/blob/master/README.md#customize-and-extends-the-client
so with a valid localconfig, is possible to extends-the-client
