### ISSUE TITLE
Reason for old MapStore2 submodule?

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode-mapstore-client#47]
Hello,
Is there a good reason to use the current old version of MapStore2 which is set to a commit? See:
https://github.com/geosolutions-it/MapStore2/tree/6de82acfe6864ca948242ff11e50127aa1caa5fd

Couldn´t we use the latest release like this one
https://github.com/geosolutions-it/MapStore2/releases/tag/v2020.01.00

@afabiani Do you have any insights? We had bumped the repo before in #2 and #27 . Are there currently breaking changes?

**Comment by afabiani** [comment]
@gannebamm MapStore has been updated to latest version.

Tipically updating MapStore requires also to update and refresh the webpack and package json of the mapstore-client
