### ISSUE TITLE
MapStore must not rely on the workspace prefix inside the style names returned by GetCapabilities

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#519]
Geoserver 2.19.x [fixed](https://github.com/geosolutions-it/geoserver/issues/315) a wrong behaviour where style names isnide workspace-specific GetCapabilities reponse were returned with the workspace prefix. 
MapStores Styled editor relied on this prefix for its functionalities, which now are broken with Geoserver 2.19.x.

Another method must be designed to retrive the fully qualified name of the style (workspace + style name).

**Comment by allyoucanmap** [comment]
@giohappy I'm investigating client side to understand how to fix this behaviour but there are some cases where it's not possible recognize the correct workspace for example when a layer uses style from the global styles/ folder mixed with other from a specific workspace.

case

- layer gs:us_states with get capabilities targeting its own specific workspace shows all the styles without prefix but there are some styles that are in the global styles folder. How should the client guess which one is from the styles folder and which not? (pophade, pophatch and polygon are in the global styles/ directory)

https://gs-stable.geo-solutions.it/geoserver/gs/us_states/wms?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by giohappy** [comment]
this is a good question. We should ask the Geoserver team.

**Comment by allyoucanmap** [comment]
@giohappy the answer is that we cannot rely on get capabilities to get information about the workspace of a style but we should use the geoserver rest api instead.

**Comment by giohappy** [comment]
@allyoucanmap so another request to do...
Having a proper metadata management for styles is more and more urgent, but since this won't happen very soon I don't see any other solution then doind this affitional request for the time being.

**Comment by giohappy** [comment]
@allyoucanmap apparently the problem also happens with the new 2.18.x, the one updated for the current GN 3.2.x. Can you please give it a look urgently?

**Comment by giohappy** [comment]
I guess this can be close @allyoucanmap right?

**Comment by allyoucanmap** [comment]
@giohappy yes
