### ISSUE TITLE
View Geostory/Dashboard loggs KeyError

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#560]
On viewing a geoApp(Geostory/ Dashboard) A key error is logged [here](https://github.com/GeoNode/geonode-mapstore-client/blob/3.3.x/mapstore2_adapter/plugins/geonode.py#L128)
Geoapp `viewer_obj` has no attribute `about`.

branch 3.3.x

**Comment by giohappy** [comment]
that's strange @marthamareal. The `convert` method (and the viewer_obj) should only be used for maps, not geoaapps. Can you please invetigate why we're hitting that methog for geoapps?

**Comment by marthamareal** [comment]
@giohappy  We are hitting the `convert` method because in the hooksets for geoapps(eg `geoapp_new_template` ) , the `initialize_context` function is used and in it the convert is used [here](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L94). (callback defined [here](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/hooksets.py#L222).

**Comment by giohappy** [comment]
ok @marthamareal so in that acse let's use a `get` for the about property, and check for its existence before using it.
