### ISSUE TITLE
Filtered Layer export fails 

### ISSUE THREAD

**Issue by AleMScof** [GeoNode/geonode-mapstore-client#565]
Hi all,

Whenever you try to export a layer that has been filtered by one of its columns and you select "download filtered dataset" the export is failing and it's throwing the error below which is misleading.

This fix has been made already in this commit: https://github.com/geosolutions-it/MapStore2/commit/510d68c303026fd9035e2d933dabe789a8e88984

And it should be backported on all GeoNode deployment ( where it's reproducible ): master,development and stable

Thus I'd like to better understand how to contribute to this project,
any guidance for PRs ?

Ty guys,
A-

## Popup: 

![image](https://user-images.githubusercontent.com/29773796/140158034-afd29a38-bd3a-4f6a-a966-6672ab5533ff.png)

## This is a sample request screen:

<img width="1162" alt="Schermata 2021-11-03 alle 18 27 36" src="https://user-images.githubusercontent.com/29773796/140158564-625f91ca-86c8-4828-8f13-c987e77f02d2.png">

**Comment by allyoucanmap** [comment]
> And it should be backported on all GeoNode deployment ( where it's reproducible ): master,development and stable
> 
> Thus I'd like to better understand how to contribute to this project,
> any guidance for PRs ?
> 

Hi @AleMScof ,

The current situation of the branches is this one

- `master` uses the `MapStore2`  stable branch version `2021.02.xx`
- `3.3.x` (development) uses the `MapStore2` stable branch version `2021.02.xx`
- `3.2.x` (stable) uses the `MapStore2` branch version `geonode-3.2.x`

This particular fix [has been not backported yet](https://github.com/geosolutions-it/MapStore2/pull/7353#issuecomment-942421177) to the stable branch, once it has been beckported the MapStore submodule can be updated with new PRs to geonode-mapstore-client for master, development and stable

hope this clarify a bit the workflow

**Comment by AleMScof** [comment]
For the geonode-mapstore-client branch 3.2.x , which is the one i am using, i can see that the submodule is pointing 2019.01.xx

Should it be updated according to your list?

`[submodule "geonode_mapstore_client/client/MapStore2"]
	path = geonode_mapstore_client/client/MapStore2
	url = https://github.com/geosolutions-it/MapStore2.git
	branch = 2019.01.xx`

Ty,
A-

**Comment by allyoucanmap** [comment]
> Should it be updated according to your list?

I would like to verify if the `branch = 2019.01.xx` has some effect in the cloning of the repository
Could you see the current commit in you sumbodule in your local repository?

```cmd
cd geonode-mapstore-client/geonode_mapstore_client/client/MapStore2
```

```cmd
git log
```
master -> MapStore2 @ d72f4bb
3.3.x -> MapStore2 @ bd4f0c6
3.2.x -> MapStore2 @ 2768e5b

I'm guessing that the branch property has no effect on the update of submodule because the commit hash stored is the one that it used by the client and it's misleading

![image](https://user-images.githubusercontent.com/19175505/140292736-3b77cde1-ea37-48a3-a854-b73e5b4270af.png)

**Comment by AleMScof** [comment]
That's true forking the repo points toward 3.2.x which is @ 2768e5b

But if you reinit the submodule through

`git submodule update --init --recursive --remote
`
commits get altered and follows the one declared in `.gitmodules`


<img width="239" alt="Schermata 2021-11-04 alle 11 55 40" src="https://user-images.githubusercontent.com/29773796/140302103-2b020bf2-cd95-4119-82fc-8c24b45c8738.png">

![image](https://user-images.githubusercontent.com/29773796/140302068-2600bf39-5839-423b-96b5-fd50d3348f4a.png)

**Comment by allyoucanmap** [comment]
thanks for checking it @AleMScof .

> But if you reinit the submodule through
> 
> git submodule update --init --recursive --remote
> commits get altered and follows the one declared in .gitmodules

I think the best solution is to update all the `.gitmodules` with the correct branches so they are consistent.

> Thus I'd like to better understand how to contribute to this project,
> any guidance for PRs ?

Could you please open the PRs updating the `.gitmodule` files for the three branches? (if not I'll try to add this fix as soon as I can)

- master -> `branch = 2021.02.xx`
- 3.3.x -> `branch = 2021.02.xx`
- 3.2.x -> `branch = geonode-3.2.x`

thanks again

**Comment by AleMScof** [comment]
Sure Stefano no problems, i'll do it. 

Thanks for your guidance, 
when you have the chance please review #544, we can contribute over there aswell if needed.

Ty
