### ISSUE TITLE
Dataset bbox exceeds the maximum extent and crash the viewer

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#576]
The dataset viewer uses `ll_bbox_polygon` to apply the bbox to the layer object. In some cases this geometry could have values that exceeds the maximum extent and in that case the application crashes.

example of dataset with wrong values, the latitude is greater than 90:
![image](https://user-images.githubusercontent.com/19175505/140893177-1ed85025-6150-40ee-8a1e-f6958a0e0d76.png)

error referring to https://openlayers.org/en/v5.3.0/doc/errors/#25

`Cannot fit empty extent provided as geometry.`

![image](https://user-images.githubusercontent.com/19175505/140893389-43eef69d-57e6-43d4-8d4b-c76309314250.png)

**Comment by giohappy** [comment]
is this still valid @allyoucanmap?
