### ISSUE TITLE
Hide admins from Share plugin

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#578]
Management of admin users permissions must be removed from the Share plugin.
The client can use the Permissions API response to see if a user has the "is_superuser" flag, which identifies admins. This has been introduced in https://github.com/GeoNode/geonode/pull/8363

**Comment by DavidQuartz** [comment]
I would like some clarity on this issue.
The title suggests that admins should be removed from the share plugin, but in the description, it seems that what should be removed should be the ability to manage admin permissions in the share plugin. I opened a pull request here to fix this issue ( #594 ) from the latter point of view. 
However, I had a discussion with @allyoucanmap about this, and he suggests we remove the admin completely not just the admin user permissions.

Can you please share some clarity, @giohappy?

**Comment by giohappy** [comment]
@DavidQuartz I don't know what your PR contains but the final result should be the complete removal of admins from the Share plugin. Leaving the admins (without any control) would be misleading and useless.
