### ISSUE TITLE
Legends are not saved in Dashboards and after saving no more legends are available to select

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#579]
Something is not saved configured or saved correctly for dashboards when a legend widget is added.

1. A legend for a map is selected when creating a legend widget
2. The legend doesn't show up after saving the dashboard
3. No legends are listed when the user tries to create a new legend widget

![dashboard and legends](https://user-images.githubusercontent.com/571129/141321436-c409c0c6-0b3b-46f3-99b7-1152a48e57ca.gif)

**Comment by allyoucanmap** [comment]
Closing in favor of #584
