### ISSUE TITLE
Search services are not saved

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode-mapstore-client#58]
# Steps to Reproduce the Problem

* I create a map and save it, this works correctly
* Create / edit a search service and save it. I test if the search works and everything is correct. The problem is when I go out and enter the Map again and the Search Service that I created disappears

# Specifications
* GeoNode version: 3.0

From the GeoNode issue: https://github.com/GeoNode/geonode/issues/5091

**Comment by afabiani** [comment]
@gannebamm see @offtherailz comments on linked MapStore2 issue

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/django-mapstore-adapter/releases/tag/2.0.4
