### ISSUE TITLE
Identify and widgets interactions not working for dashboards on mobile

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#580]
Identify popup does not open and the interactions between widgets do not work

**Comment by allyoucanmap** [comment]
@giohappy About the popup I saw that there is an hardcoded control that based on the size of map it will show or not the popup:

`const enablePopupTools = mapHeight > 400 && mapWidth > 400 && mapInfoControl;`

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/widget/MapWidget.jsx#L39

and this was a request of the issue:

> 3. The popup could generate strange behavior in too small map widgets, we can consider to deactivate the identify tool and therefore not show the popup on the user click if the map is too small

https://github.com/geosolutions-it/MapStore2/issues/4150

**Comment by allyoucanmap** [comment]
Closing in favor of #584
