### ISSUE TITLE
Thumbnail url for Geoapps is returned as base64 instead of a URL to the static image 

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#621]
When thumbnails are uploaded from the client they're sent as base64. The backend, in the case of maps, renders the posted base64 encoding into a file image, which is returned by the API as the thumbnail_url property within the resource response.

The same doesn't happen for geoapps. When the thumbnail is uploaded from the client editor, the image is saved and returned as base64,

The same mechanism implemented for maps must be adopter for geoapps, and the thumbnail_url should always return a URL to the static image.

**Comment by giohappy** [comment]
closing in favour of https://github.com/geosolutions-it/nexus-geonode/issues/483
