### ISSUE TITLE
Fix background configuration when saving a map

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#67]
from https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/73

@afabiani as you mentioned, it must be the adapter

**Comment by afabiani** [comment]
@giohappy that was caused by the "memcached" CACHE for Django, instead of only for Celery.

The "map_config" on the template was cached by Django. Disabling "memcached" on Django, fixed the issue.
