### ISSUE TITLE
Error when saving a new map

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#694]
## Expected Behavior
* When saving a new map, the map should be saved.

## Actual Behavior
* Network error

![image_2021_11_30T10_50_14_497Z](https://user-images.githubusercontent.com/12943132/144049181-914229db-2047-4dab-8717-908df45cd842.png)

## Steps to Reproduce the Problem

  1. Add a layer.
  2. Try to create a map with this layer.
  3. Wait for error.

from https://github.com/geonode/geonode/issues/8446

**Comment by marthamareal** [comment]
solved in https://github.com/GeoNode/geonode-mapstore-client/pull/695/commits
