### ISSUE TITLE
Make the client check if a resource is clonable and manage clone request error response

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#824]
A dataset or a document can only be cloned if the resource has the original files. We have cases where the original files for datasets are not stored in GeoNode, so a copy of the resource cannot be executed (at the moment).

The resources API now returns a new `is_copyable` property. The client will use this property to:

 - show the "clone" card menu item
 - show the "Save As" editor menu item

The copy endpoint now returns error 400 in case the clone is forbidden for whatever reason. The client will show a message in case the clone fails fast, i.e. returns an error even before starting any execution.

![image](https://user-images.githubusercontent.com/571129/153924843-d766c404-6b98-4887-9848-945c7a7c7d56.png)

**Comment by marthamareal** [comment]
Tested with the following steps and output:
- Move cursor to a dataset where (is_copyble=false)
 - Click on ... (arranged vertically) on a dataset card
- Verify that clone option is not available
- Click on view
- Click on View dataset
- Click on Save
- Verify that option Save As is not available
