### ISSUE TITLE
Render HTML abstract content

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#838]
Currently, the abstract field is rendered using the `raw_abstract` property. This is ok for simple abstracts, but if HTML is used to format abstract content we would get bad results (for example with bullet lists, links, etc.).

Rendering HTML in "unsafe" mode should be ok since the backend already makes security checks on submitted content when the resource metadata is edited.

Of course, editing would be problematic, since a WYSIWYG editor (as we do in metadata editing) would be required. So for the moment, we might consider disabling editing the abstract field from the client. 

What's your opinion @allyoucanmap?

**Comment by DavidQuartz** [comment]
@giohappy does this refer to disabling editing the abstract inside the Info Panel or at Edit Metadata, or both?

**Comment by marthamareal** [comment]
@giohappy, @DavidQuartz is the formatting not expected on rendering the abstract below?
![ss1.png](https://images.zenhubusercontent.com/5d1a1e04599844363331c019/59fbe445-40f6-414f-a25d-e318fa56417e)

**Comment by giohappy** [comment]
@marthamareal yes, the raw abstract is used in the info box below, since it doesn't have an HTML renderer. It should what you get when you query the CSW service (raw values).
