### ISSUE TITLE
Implement direct download action buttons

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#842]
We want to give the user the option to perform a quick download directly from the resource card and the resource preview panel.

For the moment it will be implemented as a simple call to a download link provided by a new `resource.download_url` property. 
The download URL can be requested with `Content-Type` `application/json` to receive error responses as JSON.
If the request goes fine a response with file content-disposition will be returned, which will trigger the download.

The direct download actions will be made available inside to the user if the current user has `download_resourcebase` permission granted for the resource.

The direct download buttons will be rendered:
 - as a menu item inside the resource card menu 
 - as a download icon to the left of the favorite icon (see image below)

A message box (toast?) will visualize any error returned by the request

![image](https://user-images.githubusercontent.com/571129/154679140-11f54a01-b8f2-4bc4-a7d8-f75ad31ff9ca.png)

**Comment by DavidQuartz** [comment]
@giohappy, there is already a download button which we can use in the detail panel, between the favorite and share icon (only for downloadable documents) as below 

![Screenshot 2022-02-21 at 12 10 16](https://user-images.githubusercontent.com/42542676/154953052-9fea6573-7632-4ec2-90af-9d8dc2747316.png)

Would you like it moved to the position specified in the issue?

**Comment by giohappy** [comment]
It0's fine to keep it as it is.

**Comment by marthamareal** [comment]
@giohappy @DavidQuartz, is it expected not to have this feature for resources which can not be cloned?
Am currently testing this on master.demo, but the buttons only appear on resources which can be cloned.

**Comment by marthamareal** [comment]
Okay. Thank you for the clarification.

**Comment by giohappy** [comment]
@DavidQuartz that's not true. Cloning requires original files to be available to GeoNode. We have cases where local resources don't have original files (because they weren't stored when the resource was created) but the direct download should still work for them since WPS download doesn't need the original files. 

In brief cloning and download are not directly related. Moreover, their availability to the end-user depends on permissions.

**Comment by marthamareal** [comment]
> @marthamareal did you find cases where cloning was available but download wasn't?

No, All resources i tried didn't have both.

**Comment by giohappy** [comment]
That's odd. Did you try with your own user? Were they local resources?

**Comment by marthamareal** [comment]
Found one
![res](https://user-images.githubusercontent.com/20810749/155758045-db0a10c5-51c5-4db1-88e7-48fb91087968.png)

**Comment by giohappy** [comment]
@marthamareal this case is possible. Read again my comment above. This case is expected when the data files are not available, but the resource is local and downloadable.

**Comment by marthamareal** [comment]
Tested on master demo and works as expected.
