### ISSUE TITLE
Download should be visible in card menu to anonymous users if the permission is available

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#851]
I suspect that the card menu is always hidden for anonymous users. It should be hidden only if no action is permitted to a user (anonymous or not), not on the basis of the role.
By default anonymous users have download permissions on new resources, so I expect the download menu item to be visible inside the card menu.

**Comment by marthamareal** [comment]
Tested on master demo. and works as expected.
