### ISSUE TITLE
"FeatureType Grid Widget" returns empty geometries when a spatial filter is set

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#852]
@afabiani commented on [Thu Dec 02 2021](https://github.com/GeoNode/geonode/issues/8460)

## Expected Behavior
When trying to download a dataset with a **spatial filter** applied like shown her below, I'd expect the process correctly generating the output file

![image](https://user-images.githubusercontent.com/1278021/144406072-30889586-2007-4883-b8dc-448c54760a71.png)

![image](https://user-images.githubusercontent.com/1278021/144406102-8cb867a7-1478-4698-8d20-4a656aa3a9a0.png)

## Actual Behavior
The `Download Process` fails with an `Empty Geometries Null Pointer Exception` error

![image](https://user-images.githubusercontent.com/1278021/144406279-8018e94d-3597-4b65-a411-3341ba876372.png)

## Steps to Reproduce the Problem

  1. Open the grid editor widget on a vectorial dataset
  2. Create a map filter
  3. Try to download the filtered data

## Specifications

  - GeoNode version: 4.0, 3.3, 3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

---

@luorlandini commented on [Fri Dec 03 2021](https://github.com/GeoNode/geonode/issues/8460#issuecomment-985620492)

after some investigation, the problem seems to be on the geoserver side

this is the request done to geoserver: 

url: https://localhost:8081/geoserver/ows?service=WPS&version=1.0.0&REQUEST=Execute&access_token=8K6lZPHv1Vx7poFaxgM8uDE9b0mhgw
payload: 
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:dwn="http://geoserver.org/wps/download" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" service="WPS" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd">
   <ows:Identifier>gs:Download</ows:Identifier>
   <wps:DataInputs>
      <wps:Input>
         <ows:Identifier>layerName</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>geonode:wilayas_58</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>outputFormat</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>application/zip</wps:LiteralData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>filter</ows:Identifier>
         <wps:Data>
            <wps:ComplexData mimeType="text/xml; subtype=filter/1.1"><![CDATA[<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml"><ogc:And><ogc:Intersects><ogc:PropertyName>geometry</ogc:PropertyName><gml:Polygon srsName="EPSG:3857"><gml:outerBoundaryIs><gml:LinearRing><gml:coordinates>90319.02643363085,3414964.3591960706 90319.02643363085,3991448.246372885 687801.5984746646,3991448.246372885 687801.5984746646,3414964.3591960706 90319.02643363085,3414964.3591960706</gml:coordinates></gml:LinearRing></gml:outerBoundaryIs></gml:Polygon></ogc:Intersects></ogc:And></ogc:Filter>]]></wps:ComplexData>
         </wps:Data>
      </wps:Input>
      <wps:Input>
         <ows:Identifier>cropToROI</ows:Identifier>
         <wps:Data>
            <wps:LiteralData>false</wps:LiteralData>
         </wps:Data>
      </wps:Input>
   </wps:DataInputs>
   <wps:ResponseForm>
      <wps:ResponseDocument storeExecuteResponse="true" status="true">
         <wps:Output asReference="true">
            <ows:Identifier>result</ows:Identifier>
         </wps:Output>
      </wps:ResponseDocument>
   </wps:ResponseForm>
</wps:Execute>

```
this is the response about that request: 
```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="en" service="WPS" serviceInstance="https://master.demo.geonode.org/geoserver/ows?" statusLocation="https://master.demo.geonode.org/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionStatus&amp;executionId=fba695c2-263a-40b4-aa6d-8b17a90867b4" version="1.0.0">
   <wps:Process wps:processVersion="1.0.0">
      <ows:Identifier>gs:Download</ows:Identifier>
      <ows:Title>Enterprise Download Process</ows:Title>
      <ows:Abstract>Downloads Layer Stream and provides a ZIP.</ows:Abstract>
   </wps:Process>
   <wps:Status creationTime="2021-12-03T15:20:56.688Z">
      <wps:ProcessFailed>
         <ows:ExceptionReport version="1.1.0">
            <ows:Exception exceptionCode="NoApplicableCode">
               <ows:ExceptionText>Process failed during execution
java.lang.IllegalStateException: Got an empty feature collection.
Got an empty feature collection.</ows:ExceptionText>
            </ows:Exception>
         </ows:ExceptionReport>
      </wps:ProcessFailed>
   </wps:Status>
</wps:ExecuteResponse>
```

mapstore send wps:Data, unless the ogc filter is not valid for geoserver, the problem seems to be on that side

---

@giohappy commented on [Fri Feb 04 2022](https://github.com/GeoNode/geonode/issues/8460#issuecomment-1030199812)

Notice that when the same polygon is set a ROI input to the WPS process, everything works fine.
Attributes filters are also working fine.

**Comment by giohappy** [comment]
Bug report created for MapStore https://github.com/geosolutions-it/MapStore2/issues/7893

**Comment by giohappy** [comment]
Upstream PR has been mertged.
We're waiting for its backport to the stable branch of MapStore. 
GeoNode client submodule will be aligned afterwards.

**Comment by allyoucanmap** [comment]
@giohappy @afabiani 
this fix has been ported on master and 3.3.x with these two PRs
- master https://github.com/GeoNode/geonode-mapstore-client/pull/874
- 3.3.x https://github.com/GeoNode/geonode-mapstore-client/pull/879

**Comment by giohappy** [comment]
@marthamareal to be tested

**Comment by marthamareal** [comment]
I have tested this with [master.demo](https://master.demo.geonode.org) and [development.demo](https://development.demo.geonode.org). But both are failing. see images below

![ss](https://user-images.githubusercontent.com/20810749/158782512-26033403-81ef-4fa1-b4fa-c17cacf3ed55.png)
![ss1](https://user-images.githubusercontent.com/20810749/158782481-19b12661-4ba9-4155-ae1b-9e109907e702.png)

**Comment by giohappy** [comment]
@DavidQuartz can you please inspect the WPS request and verify that the MapStore fix is actually there?

**Comment by DavidQuartz** [comment]
@giohappy I confirm that the fix is actually there. I made a quick test with the same datasets as @marthamareal on master and dev instances and both were successul.

<img width="1328" alt="Screenshot 2022-03-17 at 11 42 22" src="https://user-images.githubusercontent.com/42542676/158802092-ba66be00-1424-41e0-8c56-8d5c472aac87.png">

<img width="1900" alt="Screenshot 2022-03-17 at 11 45 18" src="https://user-images.githubusercontent.com/42542676/158802113-10ad7116-66d4-4e7b-b64c-743c8a68c0b1.png">

Seeing from the error @marthamareal is getting, it's not related to the initial GML error. I suspect it may be related to [this issue](https://github.com/geosolutions-it/MapStore2/issues/7932) on mapstore about failing exports which should currently be under investigation on the server side.

**Comment by giohappy** [comment]
@marthamareal can you confirm it's happening only for download formats except CSV? This is what the issue reported by @DavidQuartz says.

**Comment by marthamareal** [comment]
Yes that's correct. It only succeeds on CSV format

**Comment by marthamareal** [comment]
After clearing my browser `cache`, Export is successful for all available formats on both [master.demo](https://master.demo.geonode.org/) and [development.demo](https://development.demo.geonode.org/).
