### ISSUE TITLE
If a request to delete an upload fails the card must be removed from the uploads list

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#853]
We have had a case where an upload was failed and the request for its deletion (to `/upload/delete`) also failed. A refresh for the page was required to remove the upload card.

The client should remove a card if a request for deletion fails with a Not Found error, whatever the state of the upload (failed, pending, etc.).

**Comment by marthamareal** [comment]
Tested on master demo. and works as expected.
