### ISSUE TITLE
Geostory editing: investigate if it's possible to maintain the origin when switching between resource type selection

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#864]
Switching between resource types the origin always resets to the first / default one, which is annoying since the user neds to reselect the oen previously selected.

![service origin switch](https://user-images.githubusercontent.com/571129/143259213-317449eb-fd08-4a11-be11-9990663de844.gif)

**Comment by giohappy** [comment]
@DavidQuartz as reported by @tonym3nsa this should be doable with a configuration change.
If we remove defaultSource from mediaEditorSettings here

![image](https://user-images.githubusercontent.com/11991428/157653286-0229e523-6fa5-44eb-9dc9-b9f2ec26f335.png)

we should be able to maintain latest service selected while switching media type.

Can you please verify and confirm?

**Comment by marthamareal** [comment]
Tested on master demo. and works as expected.
