### ISSUE TITLE
Rename Layers Catalog to Datasets Catalog

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#896]
![image](https://user-images.githubusercontent.com/571129/161579111-2b450ffa-27d0-40ac-be50-adffadf34828.png)

**Comment by DavidQuartz** [comment]
@giohappy should we change this to Add Dataset?
![Screenshot 2022-04-04 at 15 42 02](https://user-images.githubusercontent.com/42542676/161581176-6e372fb3-81d2-49ed-9d55-95120b869959.png)
