### ISSUE TITLE
Add layer visibility toggle to legend component

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#898]
In many occasions I felt the need to be able to turn the layer off and see what's behind the dataset layer.
I think the legend component that we use for the dataset editor / viewer could be extended to include a reduced version of the layer control we have inside the TOC.  Just the toggle button for visibility and the opacity slider.

Something like this:

![image](https://user-images.githubusercontent.com/571129/161697103-1f5e8d60-4ac9-4d21-8a3e-b53a9f2f579a.png)

@allyoucanmap do you think it's feasible?

**Comment by marthamareal** [comment]
toggle is present and wroking.
