### ISSUE TITLE
Issues with filters: no debounce and dropdown closing on click

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#900]
In the example below I was searching resources for the "admin" user. As you can see from the network request the filter uses only the first input character ("a") instead of the whole word.

Moreover, I see a problem with the UI. If you click out the input box the filter dropdown gets closed. When the request completes the user has no clues that the results for the filter values have been returned inside the select.

![issue_with_filter_ux](https://user-images.githubusercontent.com/571129/161718049-1e219ac8-ee3b-45cd-bfca-09e51c03ef6a.gif)

**Comment by DavidQuartz** [comment]
@giohappy I'm not the expected behaviour we want because the general user expectation is for a dropdown to close when we click outside of it.
Otherwise it may appear to be a bug if it stays open.
What do you think, @allyoucanmap?

**Comment by giohappy** [comment]
As agree on chat, what is most relevant is 

- debounce
- the text entered by the user shouldn't be erades when he clicks away.

**Comment by marthamareal** [comment]
> the text entered by the user shouldn't be erades when he clicks away.

@DavidQuartz, @giohappy , From the chat, is the search text expected to remain in the input box when user clicks away? (Currently testing but its erased when i click away)

**Comment by giohappy** [comment]
Apparently this would require some work since  the external component doesn't support this behaviour.
We expect just the debounce at the moment.
