### ISSUE TITLE
Truncate abstract inside the metadata table inside the info box

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#919]
It's a waste of space and repetition. I would truncate the abstract with ellipsis

![image](https://user-images.githubusercontent.com/571129/163160233-8a93469c-208d-4c92-83b3-a173f8d5b743.png)

**Comment by marthamareal** [comment]
@DavidQuartz, @giohappy, I noticed that the last character is removed on Read More
![ss1.png](https://images.zenhubusercontent.com/5d1a1e04599844363331c019/ab48165d-d20a-413d-bbef-5ee4338018ea)

**Comment by giohappy** [comment]
good catch! @DavidQuartz can you submit a quick fix for that?
