### ISSUE TITLE
The upload box should accept xml and sld files along with the dataset itself

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#925]
The upload of a metadata file (.xml) and/or a style (.sld file) is forbidden unless a zip file containing those files is uploaded.
This is a regression from 3.3.x, where both metadata and style could be uploaded along with the dataset files.
Those files, if present, must have the same name as the dataset files.

**Comment by giohappy** [comment]
@ElenaGallo do we have a test for this in Cucumber?

**Comment by ElenaGallo** [comment]
@giohappy no, we don't have a specific test for that

**Comment by giohappy** [comment]
@ElenaGallo please create one and test both on master and dev
