### ISSUE TITLE
Share permissions form not showing for users in groups with manage permission

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode-mapstore-client#935]
Users in groups with manage permissions should be able to see permissions share form and manage permissions.

This could be because the client is only considering only `users` in permspec.
We also need to consider `groups` and `organizations`
### Step to reproducethe issue:
1. As an admin, Select a resource and edit share permissions
2. Add a group and assign it Manage permission (then save)
3. login as a member of the above group.
4. Notice that when you select the resource shared, you will not be able to edit permissions.

**Comment by marthamareal** [comment]
@allyoucanmap, PR https://github.com/GeoNode/geonode/pull/9117 to fix the API is merged

**Comment by giohappy** [comment]
where we are with this @marthamareal @allyoucanmap ?
