### ISSUE TITLE
Failing datasets uploads are generating double entries in the list of not processed upload

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode-mapstore-client#942]
The following code is adding entries similar to the one recieved from the processed GeoNode API

https://github.com/GeoNode/geonode-mapstore-client/blob/b989d578e217441bb0d1e2e327cae9fd6b1cdea6/geonode_mapstore_client/client/js/routes/UploadDataset.jsx#L227-L237

We should remove this behaviour to avoid a results as the following where the error card is duplicated one from upload error and one from the processed invalid responses:

![image](https://user-images.githubusercontent.com/19175505/164184987-c265b2f6-f8ea-46e6-b8bf-866569cd5830.png)

We should introduce following fixes:

- remove the card update for the failing one (snippet above)
- add a error sign in the list of card instead for the failing request with a tooltip error message

![image](https://user-images.githubusercontent.com/19175505/164190968-5c0b3a0d-bfde-48ad-8138-b29a559710cd.png)

**Comment by marthamareal** [comment]
@DavidQuartz This needs a backport to 4.x.
