### ISSUE TITLE
Show direct links and embed links inside Share panel

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#947]
The share panel at the moment shows the catalogue link only.
We need to add 

- direct link for documents (`href` attributes)
- embed link for geoapps (`embed` attribute)

Ex. for a document:

![image.png](https://images.zenhubusercontent.com/5cd43fb0fe59e12f2130c48a/2da89d0b-ccb3-4636-9942-94566707c399)

**Comment by giohappy** [comment]
@DavidQuartz with @allyoucanmap we agree that separating the blocks would look better and more clear. Something like the following

![image](https://user-images.githubusercontent.com/571129/167424832-05a10b95-d161-45e8-b419-1e422b53a904.png)

**Comment by marthamareal** [comment]
Tests pass as expected.

**Comment by allyoucanmap** [comment]
@DavidQuartz please backport this to 4.x branch

**Comment by giohappy** [comment]
I think we still miss something @DavidQuartz 

For a document we need:

 - link to the current page
 - link for embedding the page  (label should be "Embed")
 - direct link to the document (label should be "Direct link")

For apps:

 - link to the current page
 - link for embedding the page (label should be "Embed")

![image](https://user-images.githubusercontent.com/571129/167827807-9698cfd0-e0ba-4bed-b627-adb81ae21fc0.png)

![image](https://user-images.githubusercontent.com/571129/167827826-b76f5b0c-5807-4ee9-a717-62ebde88d5dc.png)


We probably can also reduce a bit vertical spacing, to save some space, and make the labels a bit smaller or more pale. They have too relevance right now.

![image](https://user-images.githubusercontent.com/571129/167828264-c946abb3-4d4f-45b8-acd6-b411d1e71743.png)
