### ISSUE TITLE
Unable to load page on Safari browser with GeoNode 4.0.x

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#954]
@manhninh commented on [Sun Apr 03 2022](https://github.com/GeoNode/geonode/issues/9022)

## Expected Behavior
Install the latest version on the master branch. Expect to work on all browsers

## Actual Behavior
Google Chrome browser has no problem but on Safari browser the screen stops.
![Screen Shot 2022-04-03 at 16 58 30](https://user-images.githubusercontent.com/13707506/161422380-4f5a6315-bdcd-4763-a027-793a7a14e99f.png)

## Steps to Reproduce the Problem

   1. Install GeoNode from master branch
   2. Access from Safari browser

## Specifications

   - GeoNode version: 4.0.0
   - Installation method: manual
   - Platform: Ubuntu

---

@t-book commented on [Thu Apr 07 2022](https://github.com/GeoNode/geonode/issues/9022#issuecomment-1091849318)

@allyoucanmap It looks safari has some problems with regex look behinds?

---

@giohappy commented on [Fri Apr 08 2022](https://github.com/GeoNode/geonode/issues/9022#issuecomment-1092682234)

@t-book I don't have Safari to test it but can you replicate it on master demo?

---

@manhninh commented on [Tue Apr 19 2022](https://github.com/GeoNode/geonode/issues/9022#issuecomment-1101968727)

@giohappy The error is still happening on Safari browser. Can you help me?

---

@gannebamm commented on [Tue Apr 26 2022](https://github.com/GeoNode/geonode/issues/9022#issuecomment-1109944126)

One of my researchers also experienced this issue, but with a 3.3.x instance.

---

@giohappy commented on [Fri May 06 2022](https://github.com/GeoNode/geonode/issues/9022#issuecomment-1119590583)

@manhninh it wasn't a priority but we are investigating right now. I will transfer this to the mapstore client repo.

**Comment by giohappy** [comment]
@DavidQuartz I was able to replicate it from my iOS device.

**Comment by DavidQuartz** [comment]
@giohappy this issue seems to be related to Mapstore. I tested [the fix suggested here](https://github.com/geosolutions-it/MapStore2/issues/8154#issuecomment-1114597658) and it works.
It seems to have been fixed in [Mapstore master branch](https://github.com/geosolutions-it/MapStore2/pull/8160) but it's yet to be back-ported to 2022.01.xx

**Comment by giohappy** [comment]
ok @DavidQuartz thx. Do you knwo when the backport will be done?

**Comment by DavidQuartz** [comment]
@giohappy According to [this comment](https://github.com/geosolutions-it/MapStore2/pull/8160#issuecomment-1117049237), it should be after 2022.01.01 has been released.
